# This file was auto-generated by Fern from our API Definition.

import typing

from ...requests.tool_parameter import ToolParameterParams
from ...requests.tool_parameters_json_schema import ToolParametersJsonSchemaParams

CreateToolRequestParametersParams = typing.Union[typing.Sequence[ToolParameterParams], ToolParametersJsonSchemaParams]
