# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.replay_conversation_item_response import ReplayConversationItemResponse
from .raw_client import AsyncRawConversationItemsClient, RawConversationItemsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ConversationItemsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConversationItemsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawConversationItemsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConversationItemsClient
        """
        return self._raw_client

    def replay(
        self,
        id: str,
        *,
        system_prompt: str,
        num_responses: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ReplayConversationItemResponse:
        """
        Returns the alternative response(s) the assistant would have
        produced for this conversation turn given changes to the agent system prompt.

        Only assistant items from ended conversations can be replayed. The
        conversation must have an associated agent.

        Parameters
        ----------
        id : str
            The ID of the conversation item to replay.

        system_prompt : str
            The system prompt to use when generating replay responses. Use this to test prompt changes against this conversation turn.

        num_responses : typing.Optional[int]
            Number of alternative responses to generate.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ReplayConversationItemResponse
            Success response

        Examples
        --------
        from phonic import Phonic

        client = Phonic(
            api_key="YOUR_API_KEY",
        )
        client.conversation_items.replay(
            id="id",
            system_prompt="system_prompt",
        )
        """
        _response = self._raw_client.replay(
            id, system_prompt=system_prompt, num_responses=num_responses, request_options=request_options
        )
        return _response.data


class AsyncConversationItemsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConversationItemsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawConversationItemsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConversationItemsClient
        """
        return self._raw_client

    async def replay(
        self,
        id: str,
        *,
        system_prompt: str,
        num_responses: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ReplayConversationItemResponse:
        """
        Returns the alternative response(s) the assistant would have
        produced for this conversation turn given changes to the agent system prompt.

        Only assistant items from ended conversations can be replayed. The
        conversation must have an associated agent.

        Parameters
        ----------
        id : str
            The ID of the conversation item to replay.

        system_prompt : str
            The system prompt to use when generating replay responses. Use this to test prompt changes against this conversation turn.

        num_responses : typing.Optional[int]
            Number of alternative responses to generate.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ReplayConversationItemResponse
            Success response

        Examples
        --------
        import asyncio

        from phonic import AsyncPhonic

        client = AsyncPhonic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conversation_items.replay(
                id="id",
                system_prompt="system_prompt",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.replay(
            id, system_prompt=system_prompt, num_responses=num_responses, request_options=request_options
        )
        return _response.data
