# This file was auto-generated by Fern from our API Definition.

import datetime as dt

import typing_extensions


class AuthCreateConversationTokenResponseParams(typing_extensions.TypedDict):
    conversation_token: str
    """
    The conversation token to use for authentication.
    """

    expires_at: dt.datetime
    """
    When the conversation token expires.
    """
