# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import os
import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.request_options import RequestOptions
from .environment import PhonicEnvironment
from .raw_client import AsyncRawPhonic, RawPhonic
from .types.post_agents_name_or_id_add_custom_phone_number_response import (
    PostAgentsNameOrIdAddCustomPhoneNumberResponse,
)
from .types.post_agents_name_or_id_remove_custom_phone_number_response import (
    PostAgentsNameOrIdRemoveCustomPhoneNumberResponse,
)

if typing.TYPE_CHECKING:
    from .agents.client import AgentsClient, AsyncAgentsClient
    from .auth.client import AsyncAuthClient, AuthClient
    from .conversations.client import AsyncConversationsClient, ConversationsClient
    from .extraction_schemas.client import AsyncExtractionSchemasClient, ExtractionSchemasClient
    from .projects.client import AsyncProjectsClient, ProjectsClient
    from .tools.client import AsyncToolsClient, ToolsClient
    from .voices.client import AsyncVoicesClient, VoicesClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class Phonic:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    environment : PhonicEnvironment
        The environment to use for requests from the client. from .environment import PhonicEnvironment



        Defaults to PhonicEnvironment.DEFAULT



    api_key : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from phonic import Phonic

    client = Phonic(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        environment: PhonicEnvironment = PhonicEnvironment.DEFAULT,
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("PHONIC_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = SyncClientWrapper(
            environment=environment,
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._raw_client = RawPhonic(client_wrapper=self._client_wrapper)
        self._agents: typing.Optional[AgentsClient] = None
        self._tools: typing.Optional[ToolsClient] = None
        self._extraction_schemas: typing.Optional[ExtractionSchemasClient] = None
        self._voices: typing.Optional[VoicesClient] = None
        self._conversations: typing.Optional[ConversationsClient] = None
        self._auth: typing.Optional[AuthClient] = None
        self._projects: typing.Optional[ProjectsClient] = None

    @property
    def with_raw_response(self) -> RawPhonic:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPhonic
        """
        return self._raw_client

    def post_agents_name_or_id_add_custom_phone_number(
        self,
        name_or_id: str,
        *,
        phone_number: str,
        project: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostAgentsNameOrIdAddCustomPhoneNumberResponse:
        """
        Adds a custom phone number to an agent. The user must configure their SIP trunk to point to Phonic's SIP server.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the agent.

        phone_number : str
            The E.164 formatted phone number to add (e.g., "+15551234567").

        project : typing.Optional[str]
            The name of the project containing the agent. Only used when `nameOrId` is a name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostAgentsNameOrIdAddCustomPhoneNumberResponse
            Success response

        Examples
        --------
        from phonic import Phonic

        client = Phonic(
            api_key="YOUR_API_KEY",
        )
        client.post_agents_name_or_id_add_custom_phone_number(
            name_or_id="nameOrId",
            project="main",
            phone_number="+15551234567",
        )
        """
        _response = self._raw_client.post_agents_name_or_id_add_custom_phone_number(
            name_or_id, phone_number=phone_number, project=project, request_options=request_options
        )
        return _response.data

    def post_agents_name_or_id_remove_custom_phone_number(
        self,
        name_or_id: str,
        *,
        phone_number: str,
        project: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostAgentsNameOrIdRemoveCustomPhoneNumberResponse:
        """
        Removes a custom phone number from an agent.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the agent.

        phone_number : str
            The E.164 formatted phone number to remove (e.g., "+15551234567").

        project : typing.Optional[str]
            The name of the project containing the agent. Only used when `nameOrId` is a name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostAgentsNameOrIdRemoveCustomPhoneNumberResponse
            Success response

        Examples
        --------
        from phonic import Phonic

        client = Phonic(
            api_key="YOUR_API_KEY",
        )
        client.post_agents_name_or_id_remove_custom_phone_number(
            name_or_id="nameOrId",
            project="main",
            phone_number="+15551234567",
        )
        """
        _response = self._raw_client.post_agents_name_or_id_remove_custom_phone_number(
            name_or_id, phone_number=phone_number, project=project, request_options=request_options
        )
        return _response.data

    @property
    def agents(self):
        if self._agents is None:
            from .agents.client import AgentsClient  # noqa: E402

            self._agents = AgentsClient(client_wrapper=self._client_wrapper)
        return self._agents

    @property
    def tools(self):
        if self._tools is None:
            from .tools.client import ToolsClient  # noqa: E402

            self._tools = ToolsClient(client_wrapper=self._client_wrapper)
        return self._tools

    @property
    def extraction_schemas(self):
        if self._extraction_schemas is None:
            from .extraction_schemas.client import ExtractionSchemasClient  # noqa: E402

            self._extraction_schemas = ExtractionSchemasClient(client_wrapper=self._client_wrapper)
        return self._extraction_schemas

    @property
    def voices(self):
        if self._voices is None:
            from .voices.client import VoicesClient  # noqa: E402

            self._voices = VoicesClient(client_wrapper=self._client_wrapper)
        return self._voices

    @property
    def conversations(self):
        if self._conversations is None:
            from .conversations.client import ConversationsClient  # noqa: E402

            self._conversations = ConversationsClient(client_wrapper=self._client_wrapper)
        return self._conversations

    @property
    def auth(self):
        if self._auth is None:
            from .auth.client import AuthClient  # noqa: E402

            self._auth = AuthClient(client_wrapper=self._client_wrapper)
        return self._auth

    @property
    def projects(self):
        if self._projects is None:
            from .projects.client import ProjectsClient  # noqa: E402

            self._projects = ProjectsClient(client_wrapper=self._client_wrapper)
        return self._projects


class AsyncPhonic:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    environment : PhonicEnvironment
        The environment to use for requests from the client. from .environment import PhonicEnvironment



        Defaults to PhonicEnvironment.DEFAULT



    api_key : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    Examples
    --------
    from phonic import AsyncPhonic

    client = AsyncPhonic(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        environment: PhonicEnvironment = PhonicEnvironment.DEFAULT,
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = os.getenv("PHONIC_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = AsyncClientWrapper(
            environment=environment,
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
        )
        self._raw_client = AsyncRawPhonic(client_wrapper=self._client_wrapper)
        self._agents: typing.Optional[AsyncAgentsClient] = None
        self._tools: typing.Optional[AsyncToolsClient] = None
        self._extraction_schemas: typing.Optional[AsyncExtractionSchemasClient] = None
        self._voices: typing.Optional[AsyncVoicesClient] = None
        self._conversations: typing.Optional[AsyncConversationsClient] = None
        self._auth: typing.Optional[AsyncAuthClient] = None
        self._projects: typing.Optional[AsyncProjectsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawPhonic:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPhonic
        """
        return self._raw_client

    async def post_agents_name_or_id_add_custom_phone_number(
        self,
        name_or_id: str,
        *,
        phone_number: str,
        project: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostAgentsNameOrIdAddCustomPhoneNumberResponse:
        """
        Adds a custom phone number to an agent. The user must configure their SIP trunk to point to Phonic's SIP server.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the agent.

        phone_number : str
            The E.164 formatted phone number to add (e.g., "+15551234567").

        project : typing.Optional[str]
            The name of the project containing the agent. Only used when `nameOrId` is a name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostAgentsNameOrIdAddCustomPhoneNumberResponse
            Success response

        Examples
        --------
        import asyncio

        from phonic import AsyncPhonic

        client = AsyncPhonic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.post_agents_name_or_id_add_custom_phone_number(
                name_or_id="nameOrId",
                project="main",
                phone_number="+15551234567",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_agents_name_or_id_add_custom_phone_number(
            name_or_id, phone_number=phone_number, project=project, request_options=request_options
        )
        return _response.data

    async def post_agents_name_or_id_remove_custom_phone_number(
        self,
        name_or_id: str,
        *,
        phone_number: str,
        project: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostAgentsNameOrIdRemoveCustomPhoneNumberResponse:
        """
        Removes a custom phone number from an agent.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the agent.

        phone_number : str
            The E.164 formatted phone number to remove (e.g., "+15551234567").

        project : typing.Optional[str]
            The name of the project containing the agent. Only used when `nameOrId` is a name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostAgentsNameOrIdRemoveCustomPhoneNumberResponse
            Success response

        Examples
        --------
        import asyncio

        from phonic import AsyncPhonic

        client = AsyncPhonic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.post_agents_name_or_id_remove_custom_phone_number(
                name_or_id="nameOrId",
                project="main",
                phone_number="+15551234567",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_agents_name_or_id_remove_custom_phone_number(
            name_or_id, phone_number=phone_number, project=project, request_options=request_options
        )
        return _response.data

    @property
    def agents(self):
        if self._agents is None:
            from .agents.client import AsyncAgentsClient  # noqa: E402

            self._agents = AsyncAgentsClient(client_wrapper=self._client_wrapper)
        return self._agents

    @property
    def tools(self):
        if self._tools is None:
            from .tools.client import AsyncToolsClient  # noqa: E402

            self._tools = AsyncToolsClient(client_wrapper=self._client_wrapper)
        return self._tools

    @property
    def extraction_schemas(self):
        if self._extraction_schemas is None:
            from .extraction_schemas.client import AsyncExtractionSchemasClient  # noqa: E402

            self._extraction_schemas = AsyncExtractionSchemasClient(client_wrapper=self._client_wrapper)
        return self._extraction_schemas

    @property
    def voices(self):
        if self._voices is None:
            from .voices.client import AsyncVoicesClient  # noqa: E402

            self._voices = AsyncVoicesClient(client_wrapper=self._client_wrapper)
        return self._voices

    @property
    def conversations(self):
        if self._conversations is None:
            from .conversations.client import AsyncConversationsClient  # noqa: E402

            self._conversations = AsyncConversationsClient(client_wrapper=self._client_wrapper)
        return self._conversations

    @property
    def auth(self):
        if self._auth is None:
            from .auth.client import AsyncAuthClient  # noqa: E402

            self._auth = AsyncAuthClient(client_wrapper=self._client_wrapper)
        return self._auth

    @property
    def projects(self):
        if self._projects is None:
            from .projects.client import AsyncProjectsClient  # noqa: E402

            self._projects = AsyncProjectsClient(client_wrapper=self._client_wrapper)
        return self._projects
