# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.outbound_call_initiated_response import OutboundCallInitiatedResponse
from ...types.outbound_dry_run_response import OutboundDryRunResponse

ConversationsOutboundCallResponse = typing.Union[OutboundDryRunResponse, OutboundCallInitiatedResponse]
