# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .conversations_sip_outbound_call_request_sip_media_encryption import (
    ConversationsSipOutboundCallRequestSipMediaEncryption,
)
from .conversations_sip_outbound_call_request_sip_transport import ConversationsSipOutboundCallRequestSipTransport


class ConversationsSipOutboundCallRequestSip(UncheckedBaseModel):
    """
    SIP trunk settings for the outbound trunk created for this call.
    """

    transport: typing.Optional[ConversationsSipOutboundCallRequestSipTransport] = pydantic.Field(default=None)
    """
    SIP signaling transport used for this call. The SIP address must not carry a `;transport=` parameter; set it here instead.
    """

    media_encryption: typing.Optional[ConversationsSipOutboundCallRequestSipMediaEncryption] = pydantic.Field(
        default=None
    )
    """
    Whether media (SRTP) encryption is used on this call.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
