# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.sip_outbound_call_initiated_response import SipOutboundCallInitiatedResponse
from ...types.sip_outbound_dry_run_response import SipOutboundDryRunResponse

ConversationsSipOutboundCallResponse = typing.Union[SipOutboundDryRunResponse, SipOutboundCallInitiatedResponse]
