# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.get_conversation_by_external_id_response import GetConversationByExternalIdResponse
from ...types.list_conversations_response import ListConversationsResponse

ConversationsListResponse = typing.Union[ListConversationsResponse, GetConversationByExternalIdResponse]
