# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...requests.agent import AgentParams


class AgentsUpdateResponseParams(typing_extensions.TypedDict):
    success: bool
    """
    Whether the agent was updated successfully.
    """

    version_number: int
    """
    The version number of the agent after the update.
    """

    agent: AgentParams
    """
    The updated agent.
    """
