# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agents_add_custom_phone_number_request_sip_media_encryption import (
    AgentsAddCustomPhoneNumberRequestSipMediaEncryption,
)
from ..types.agents_add_custom_phone_number_request_sip_transport import AgentsAddCustomPhoneNumberRequestSipTransport


class AgentsAddCustomPhoneNumberRequestSipParams(typing_extensions.TypedDict):
    """
    SIP trunk settings for this phone number, applied to both its inbound trunk and the trunk created for each outbound call. Set at creation; remove and re-add the number to change them.
    """

    transport: typing_extensions.NotRequired[AgentsAddCustomPhoneNumberRequestSipTransport]
    """
    SIP signaling transport used for calls on this phone number. The SIP address must not carry a `;transport=` parameter; set it here instead.
    """

    media_encryption: typing_extensions.NotRequired[AgentsAddCustomPhoneNumberRequestSipMediaEncryption]
    """
    Whether media (SRTP) encryption is used on calls on this phone number.
    """
