# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class AgentsUpdatePhoneNumberRequestConfigurationEndpointParams(typing_extensions.TypedDict):
    """
    When not `null`, the agent will call this endpoint to get configuration options for calls on this phone number.
    """

    url: str
    """
    URL to call
    """

    headers: typing_extensions.NotRequired[typing.Dict[str, str]]
    """
    Object of key-value pairs.
    """

    timeout_ms: typing_extensions.NotRequired[int]
    """
    Timeout in milliseconds for the endpoint call.
    """
