# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ConversationsOutboundCallResponseParams(typing_extensions.TypedDict):
    dry_run: bool
    """
    Always true for this response.
    """
