# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .conversations_evaluate_response_evaluation import ConversationsEvaluateResponseEvaluationParams


class ConversationsEvaluateResponseParams(typing_extensions.TypedDict):
    evaluation: ConversationsEvaluateResponseEvaluationParams
