# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ConversationsReplayResponseParams(typing_extensions.TypedDict):
    message: str
    """
    Confirmation that the replay has started.
    """
