# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ConversationsDeleteResponseParams(typing_extensions.TypedDict):
    success: bool
    """
    Whether the conversation was deleted successfully.
    """
