# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.conversations_sip_outbound_call_request_sip_media_encryption import (
    ConversationsSipOutboundCallRequestSipMediaEncryption,
)
from ..types.conversations_sip_outbound_call_request_sip_transport import (
    ConversationsSipOutboundCallRequestSipTransport,
)


class ConversationsSipOutboundCallRequestSipParams(typing_extensions.TypedDict):
    """
    SIP trunk settings for the outbound trunk created for this call.
    """

    transport: typing_extensions.NotRequired[ConversationsSipOutboundCallRequestSipTransport]
    """
    SIP signaling transport used for this call. The SIP address must not carry a `;transport=` parameter; set it here instead.
    """

    media_encryption: typing_extensions.NotRequired[ConversationsSipOutboundCallRequestSipMediaEncryption]
    """
    Whether media (SRTP) encryption is used on this call.
    """
