# This file was auto-generated by Fern from our API Definition.

import typing

from ...requests.get_conversation_by_external_id_response import GetConversationByExternalIdResponseParams
from ...requests.list_conversations_response import ListConversationsResponseParams

ConversationsListResponseParams = typing.Union[
    ListConversationsResponseParams, GetConversationByExternalIdResponseParams
]
