# This file was auto-generated by Fern from our API Definition.

import typing

from ...requests.outbound_call_initiated_response import OutboundCallInitiatedResponseParams
from ...requests.outbound_dry_run_response import OutboundDryRunResponseParams

ConversationsOutboundCallResponseParams = typing.Union[
    OutboundDryRunResponseParams, OutboundCallInitiatedResponseParams
]
