# This file was auto-generated by Fern from our API Definition.

import typing

from ...requests.sip_outbound_call_initiated_response import SipOutboundCallInitiatedResponseParams
from ...requests.sip_outbound_dry_run_response import SipOutboundDryRunResponseParams

ConversationsSipOutboundCallResponseParams = typing.Union[
    SipOutboundDryRunResponseParams, SipOutboundCallInitiatedResponseParams
]
