# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class ConversationsOutboundCallResponseParams(typing_extensions.TypedDict):
    conversation_id: typing.Optional[typing.Any]
    """
    Always null when `dry_run` is true.
    """

    dry_run: bool
    """
    Always true for this response.
    """
