# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_external_storage_policy_request_addressing_style import (
        CreateExternalStoragePolicyRequestAddressingStyle,
    )
    from .external_storage_policies_create_response import ExternalStoragePoliciesCreateResponse
    from .external_storage_policies_delete_response import ExternalStoragePoliciesDeleteResponse
    from .external_storage_policies_get_response import ExternalStoragePoliciesGetResponse
    from .external_storage_policies_list_response import ExternalStoragePoliciesListResponse
    from .external_storage_policies_update_response import ExternalStoragePoliciesUpdateResponse
    from .update_external_storage_policy_request_addressing_style import (
        UpdateExternalStoragePolicyRequestAddressingStyle,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CreateExternalStoragePolicyRequestAddressingStyle": ".create_external_storage_policy_request_addressing_style",
    "ExternalStoragePoliciesCreateResponse": ".external_storage_policies_create_response",
    "ExternalStoragePoliciesDeleteResponse": ".external_storage_policies_delete_response",
    "ExternalStoragePoliciesGetResponse": ".external_storage_policies_get_response",
    "ExternalStoragePoliciesListResponse": ".external_storage_policies_list_response",
    "ExternalStoragePoliciesUpdateResponse": ".external_storage_policies_update_response",
    "UpdateExternalStoragePolicyRequestAddressingStyle": ".update_external_storage_policy_request_addressing_style",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateExternalStoragePolicyRequestAddressingStyle",
    "ExternalStoragePoliciesCreateResponse",
    "ExternalStoragePoliciesDeleteResponse",
    "ExternalStoragePoliciesGetResponse",
    "ExternalStoragePoliciesListResponse",
    "ExternalStoragePoliciesUpdateResponse",
    "UpdateExternalStoragePolicyRequestAddressingStyle",
]
