# This file was auto-generated by Fern from our API Definition.

import typing

CreateExternalStoragePolicyRequestAddressingStyle = typing.Union[typing.Literal["auto", "virtual", "path"], typing.Any]
