# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .add_system_message_payload import AddSystemMessagePayload
    from .agent import Agent
    from .agent_audio_format import AgentAudioFormat
    from .agent_background_noise import AgentBackgroundNoise
    from .agent_configuration_endpoint import AgentConfigurationEndpoint
    from .agent_integration import AgentIntegration
    from .agent_intelligence_level import AgentIntelligenceLevel
    from .agent_multilingual_mode import AgentMultilingualMode
    from .agent_project import AgentProject
    from .agent_pronunciation_dictionary_item import AgentPronunciationDictionaryItem
    from .agent_template_variables_value import AgentTemplateVariablesValue
    from .agent_tools_item import AgentToolsItem
    from .api_key_with_secret import ApiKeyWithSecret
    from .assistant_chose_not_to_respond_payload import AssistantChoseNotToRespondPayload
    from .assistant_ended_conversation_payload import AssistantEndedConversationPayload
    from .assistant_finished_speaking_payload import AssistantFinishedSpeakingPayload
    from .assistant_started_speaking_payload import AssistantStartedSpeakingPayload
    from .audio_chunk_payload import AudioChunkPayload
    from .audio_chunk_response_payload import AudioChunkResponsePayload
    from .bad_request_error_body import BadRequestErrorBody
    from .basic_error import BasicError
    from .basic_error_error import BasicErrorError
    from .built_in_tool_config import BuiltInToolConfig
    from .built_in_tool_config_speech_before_tool_call import BuiltInToolConfigSpeechBeforeToolCall
    from .built_in_tool_configs import BuiltInToolConfigs
    from .built_in_tool_definition import BuiltInToolDefinition
    from .built_in_tool_definition_name import BuiltInToolDefinitionName
    from .config_options import ConfigOptions
    from .config_options_background_noise import ConfigOptionsBackgroundNoise
    from .config_options_configuration_endpoint import ConfigOptionsConfigurationEndpoint
    from .config_options_data_retention_policy import ConfigOptionsDataRetentionPolicy
    from .config_options_data_retention_policy_audio_recordings import ConfigOptionsDataRetentionPolicyAudioRecordings
    from .config_options_data_retention_policy_audio_recordings_audio_recordings import (
        ConfigOptionsDataRetentionPolicyAudioRecordingsAudioRecordings,
    )
    from .config_options_data_retention_policy_audio_recordings_transcripts import (
        ConfigOptionsDataRetentionPolicyAudioRecordingsTranscripts,
    )
    from .config_options_data_retention_policy_zero import ConfigOptionsDataRetentionPolicyZero
    from .config_options_input_format import ConfigOptionsInputFormat
    from .config_options_intelligence_level import ConfigOptionsIntelligenceLevel
    from .config_options_multilingual_mode import ConfigOptionsMultilingualMode
    from .config_options_outbound_number_pool import ConfigOptionsOutboundNumberPool
    from .config_options_output_format import ConfigOptionsOutputFormat
    from .config_options_pronunciation_dictionary_item import ConfigOptionsPronunciationDictionaryItem
    from .config_options_tasks_item import ConfigOptionsTasksItem
    from .config_payload import ConfigPayload
    from .conversation import Conversation
    from .conversation_agent import ConversationAgent
    from .conversation_analysis import ConversationAnalysis
    from .conversation_background_noise import ConversationBackgroundNoise
    from .conversation_call_info import ConversationCallInfo
    from .conversation_created_payload import ConversationCreatedPayload
    from .conversation_deletion_info import ConversationDeletionInfo
    from .conversation_ended_by import ConversationEndedBy
    from .conversation_eval import ConversationEval
    from .conversation_eval_prompt import ConversationEvalPrompt
    from .conversation_eval_prompt_info import ConversationEvalPromptInfo
    from .conversation_eval_result import ConversationEvalResult
    from .conversation_evaluation import ConversationEvaluation
    from .conversation_evaluation_result import ConversationEvaluationResult
    from .conversation_evaluation_result_prompt import ConversationEvaluationResultPrompt
    from .conversation_evaluation_result_result import ConversationEvaluationResultResult
    from .conversation_extraction import ConversationExtraction
    from .conversation_extraction_schema import ConversationExtractionSchema
    from .conversation_item import ConversationItem
    from .conversation_item_role import ConversationItemRole
    from .conversation_item_tool_calls_item import ConversationItemToolCallsItem
    from .conversation_item_tool_calls_item_request_body import ConversationItemToolCallsItemRequestBody
    from .conversation_item_tool_calls_item_tool import ConversationItemToolCallsItemTool
    from .conversation_multilingual_mode import ConversationMultilingualMode
    from .conversation_origin import ConversationOrigin
    from .conversation_project import ConversationProject
    from .conversation_pronunciation_dictionary_item import ConversationPronunciationDictionaryItem
    from .conversations_list_response_conversation import ConversationsListResponseConversation
    from .conversations_list_response_conversations import ConversationsListResponseConversations
    from .conversations_list_response_conversations_pagination import ConversationsListResponseConversationsPagination
    from .create_agent_request import CreateAgentRequest
    from .create_agent_request_audio_format import CreateAgentRequestAudioFormat
    from .create_agent_request_background_noise import CreateAgentRequestBackgroundNoise
    from .create_agent_request_configuration_endpoint import CreateAgentRequestConfigurationEndpoint
    from .create_agent_request_intelligence_level import CreateAgentRequestIntelligenceLevel
    from .create_agent_request_multilingual_mode import CreateAgentRequestMultilingualMode
    from .create_agent_request_phone_number import CreateAgentRequestPhoneNumber
    from .create_agent_request_pronunciation_dictionary_item import CreateAgentRequestPronunciationDictionaryItem
    from .create_agent_request_template_variables_value import CreateAgentRequestTemplateVariablesValue
    from .create_agent_request_tools_item import CreateAgentRequestToolsItem
    from .data_retention_policy import DataRetentionPolicy
    from .data_retention_policy_audio_recordings import DataRetentionPolicyAudioRecordings
    from .data_retention_policy_audio_recordings_audio_recordings import (
        DataRetentionPolicyAudioRecordingsAudioRecordings,
    )
    from .data_retention_policy_audio_recordings_transcripts import DataRetentionPolicyAudioRecordingsTranscripts
    from .data_retention_policy_zero import DataRetentionPolicyZero
    from .dtmf_payload import DtmfPayload
    from .error import Error
    from .error_payload import ErrorPayload
    from .error_payload_error import ErrorPayloadError
    from .extraction_field import ExtractionField
    from .extraction_field_type import ExtractionFieldType
    from .extraction_schema import ExtractionSchema
    from .generate_reply_payload import GenerateReplyPayload
    from .inline_web_socket_tool import InlineWebSocketTool
    from .inline_web_socket_tool_execution_mode import InlineWebSocketToolExecutionMode
    from .input_cancelled_payload import InputCancelledPayload
    from .input_text_payload import InputTextPayload
    from .language_code import LanguageCode
    from .mute_payload import MutePayload
    from .open_ai_function import OpenAiFunction
    from .open_ai_function_parameters import OpenAiFunctionParameters
    from .open_ai_tool import OpenAiTool
    from .outbound_call_config import OutboundCallConfig
    from .outbound_call_config_background_noise import OutboundCallConfigBackgroundNoise
    from .outbound_call_config_configuration_endpoint import OutboundCallConfigConfigurationEndpoint
    from .outbound_call_config_intelligence_level import OutboundCallConfigIntelligenceLevel
    from .outbound_call_config_multilingual_mode import OutboundCallConfigMultilingualMode
    from .outbound_call_config_pronunciation_dictionary_item import OutboundCallConfigPronunciationDictionaryItem
    from .outbound_call_config_tools_item import OutboundCallConfigToolsItem
    from .outbound_call_initiated_response import OutboundCallInitiatedResponse
    from .outbound_dry_run_response import OutboundDryRunResponse
    from .outbound_number_pool import OutboundNumberPool
    from .project import Project
    from .project_default_agent import ProjectDefaultAgent
    from .ready_to_start_conversation_payload import ReadyToStartConversationPayload
    from .replay_conversation_item_response import ReplayConversationItemResponse
    from .replay_conversation_item_response_responses_item import ReplayConversationItemResponseResponsesItem
    from .replay_tool_call import ReplayToolCall
    from .replay_tool_call_endpoint_method import ReplayToolCallEndpointMethod
    from .replay_tool_call_tool import ReplayToolCallTool
    from .reset_payload import ResetPayload
    from .say_payload import SayPayload
    from .set_external_id_payload import SetExternalIdPayload
    from .sip_call_error import SipCallError
    from .sip_call_error_error import SipCallErrorError
    from .sip_call_error_error_code import SipCallErrorErrorCode
    from .sip_outbound_call_initiated_response import SipOutboundCallInitiatedResponse
    from .sip_outbound_dry_run_response import SipOutboundDryRunResponse
    from .task import Task
    from .tool import Tool
    from .tool_call_interrupted_payload import ToolCallInterruptedPayload
    from .tool_call_output_payload import ToolCallOutputPayload
    from .tool_call_output_processed_payload import ToolCallOutputProcessedPayload
    from .tool_call_output_processed_payload_tool import ToolCallOutputProcessedPayloadTool
    from .tool_call_payload import ToolCallPayload
    from .tool_definition import ToolDefinition
    from .tool_endpoint_method import ToolEndpointMethod
    from .tool_execution_mode import ToolExecutionMode
    from .tool_name import ToolName
    from .tool_parameter import ToolParameter
    from .tool_parameter_item_type import ToolParameterItemType
    from .tool_parameter_location import ToolParameterLocation
    from .tool_parameter_type import ToolParameterType
    from .tool_project import ToolProject
    from .tool_speech_before_tool_call import ToolSpeechBeforeToolCall
    from .tool_type import ToolType
    from .unmute_payload import UnmutePayload
    from .update_system_prompt_payload import UpdateSystemPromptPayload
    from .update_tools_subset_payload import UpdateToolsSubsetPayload
    from .user_finished_speaking_payload import UserFinishedSpeakingPayload
    from .user_started_speaking_payload import UserStartedSpeakingPayload
    from .validation_error import ValidationError
    from .validation_error_error import ValidationErrorError
    from .voice import Voice
    from .warning_payload import WarningPayload
    from .warning_payload_warning import WarningPayloadWarning
_dynamic_imports: typing.Dict[str, str] = {
    "AddSystemMessagePayload": ".add_system_message_payload",
    "Agent": ".agent",
    "AgentAudioFormat": ".agent_audio_format",
    "AgentBackgroundNoise": ".agent_background_noise",
    "AgentConfigurationEndpoint": ".agent_configuration_endpoint",
    "AgentIntegration": ".agent_integration",
    "AgentIntelligenceLevel": ".agent_intelligence_level",
    "AgentMultilingualMode": ".agent_multilingual_mode",
    "AgentProject": ".agent_project",
    "AgentPronunciationDictionaryItem": ".agent_pronunciation_dictionary_item",
    "AgentTemplateVariablesValue": ".agent_template_variables_value",
    "AgentToolsItem": ".agent_tools_item",
    "ApiKeyWithSecret": ".api_key_with_secret",
    "AssistantChoseNotToRespondPayload": ".assistant_chose_not_to_respond_payload",
    "AssistantEndedConversationPayload": ".assistant_ended_conversation_payload",
    "AssistantFinishedSpeakingPayload": ".assistant_finished_speaking_payload",
    "AssistantStartedSpeakingPayload": ".assistant_started_speaking_payload",
    "AudioChunkPayload": ".audio_chunk_payload",
    "AudioChunkResponsePayload": ".audio_chunk_response_payload",
    "BadRequestErrorBody": ".bad_request_error_body",
    "BasicError": ".basic_error",
    "BasicErrorError": ".basic_error_error",
    "BuiltInToolConfig": ".built_in_tool_config",
    "BuiltInToolConfigSpeechBeforeToolCall": ".built_in_tool_config_speech_before_tool_call",
    "BuiltInToolConfigs": ".built_in_tool_configs",
    "BuiltInToolDefinition": ".built_in_tool_definition",
    "BuiltInToolDefinitionName": ".built_in_tool_definition_name",
    "ConfigOptions": ".config_options",
    "ConfigOptionsBackgroundNoise": ".config_options_background_noise",
    "ConfigOptionsConfigurationEndpoint": ".config_options_configuration_endpoint",
    "ConfigOptionsDataRetentionPolicy": ".config_options_data_retention_policy",
    "ConfigOptionsDataRetentionPolicyAudioRecordings": ".config_options_data_retention_policy_audio_recordings",
    "ConfigOptionsDataRetentionPolicyAudioRecordingsAudioRecordings": ".config_options_data_retention_policy_audio_recordings_audio_recordings",
    "ConfigOptionsDataRetentionPolicyAudioRecordingsTranscripts": ".config_options_data_retention_policy_audio_recordings_transcripts",
    "ConfigOptionsDataRetentionPolicyZero": ".config_options_data_retention_policy_zero",
    "ConfigOptionsInputFormat": ".config_options_input_format",
    "ConfigOptionsIntelligenceLevel": ".config_options_intelligence_level",
    "ConfigOptionsMultilingualMode": ".config_options_multilingual_mode",
    "ConfigOptionsOutboundNumberPool": ".config_options_outbound_number_pool",
    "ConfigOptionsOutputFormat": ".config_options_output_format",
    "ConfigOptionsPronunciationDictionaryItem": ".config_options_pronunciation_dictionary_item",
    "ConfigOptionsTasksItem": ".config_options_tasks_item",
    "ConfigPayload": ".config_payload",
    "Conversation": ".conversation",
    "ConversationAgent": ".conversation_agent",
    "ConversationAnalysis": ".conversation_analysis",
    "ConversationBackgroundNoise": ".conversation_background_noise",
    "ConversationCallInfo": ".conversation_call_info",
    "ConversationCreatedPayload": ".conversation_created_payload",
    "ConversationDeletionInfo": ".conversation_deletion_info",
    "ConversationEndedBy": ".conversation_ended_by",
    "ConversationEval": ".conversation_eval",
    "ConversationEvalPrompt": ".conversation_eval_prompt",
    "ConversationEvalPromptInfo": ".conversation_eval_prompt_info",
    "ConversationEvalResult": ".conversation_eval_result",
    "ConversationEvaluation": ".conversation_evaluation",
    "ConversationEvaluationResult": ".conversation_evaluation_result",
    "ConversationEvaluationResultPrompt": ".conversation_evaluation_result_prompt",
    "ConversationEvaluationResultResult": ".conversation_evaluation_result_result",
    "ConversationExtraction": ".conversation_extraction",
    "ConversationExtractionSchema": ".conversation_extraction_schema",
    "ConversationItem": ".conversation_item",
    "ConversationItemRole": ".conversation_item_role",
    "ConversationItemToolCallsItem": ".conversation_item_tool_calls_item",
    "ConversationItemToolCallsItemRequestBody": ".conversation_item_tool_calls_item_request_body",
    "ConversationItemToolCallsItemTool": ".conversation_item_tool_calls_item_tool",
    "ConversationMultilingualMode": ".conversation_multilingual_mode",
    "ConversationOrigin": ".conversation_origin",
    "ConversationProject": ".conversation_project",
    "ConversationPronunciationDictionaryItem": ".conversation_pronunciation_dictionary_item",
    "ConversationsListResponseConversation": ".conversations_list_response_conversation",
    "ConversationsListResponseConversations": ".conversations_list_response_conversations",
    "ConversationsListResponseConversationsPagination": ".conversations_list_response_conversations_pagination",
    "CreateAgentRequest": ".create_agent_request",
    "CreateAgentRequestAudioFormat": ".create_agent_request_audio_format",
    "CreateAgentRequestBackgroundNoise": ".create_agent_request_background_noise",
    "CreateAgentRequestConfigurationEndpoint": ".create_agent_request_configuration_endpoint",
    "CreateAgentRequestIntelligenceLevel": ".create_agent_request_intelligence_level",
    "CreateAgentRequestMultilingualMode": ".create_agent_request_multilingual_mode",
    "CreateAgentRequestPhoneNumber": ".create_agent_request_phone_number",
    "CreateAgentRequestPronunciationDictionaryItem": ".create_agent_request_pronunciation_dictionary_item",
    "CreateAgentRequestTemplateVariablesValue": ".create_agent_request_template_variables_value",
    "CreateAgentRequestToolsItem": ".create_agent_request_tools_item",
    "DataRetentionPolicy": ".data_retention_policy",
    "DataRetentionPolicyAudioRecordings": ".data_retention_policy_audio_recordings",
    "DataRetentionPolicyAudioRecordingsAudioRecordings": ".data_retention_policy_audio_recordings_audio_recordings",
    "DataRetentionPolicyAudioRecordingsTranscripts": ".data_retention_policy_audio_recordings_transcripts",
    "DataRetentionPolicyZero": ".data_retention_policy_zero",
    "DtmfPayload": ".dtmf_payload",
    "Error": ".error",
    "ErrorPayload": ".error_payload",
    "ErrorPayloadError": ".error_payload_error",
    "ExtractionField": ".extraction_field",
    "ExtractionFieldType": ".extraction_field_type",
    "ExtractionSchema": ".extraction_schema",
    "GenerateReplyPayload": ".generate_reply_payload",
    "InlineWebSocketTool": ".inline_web_socket_tool",
    "InlineWebSocketToolExecutionMode": ".inline_web_socket_tool_execution_mode",
    "InputCancelledPayload": ".input_cancelled_payload",
    "InputTextPayload": ".input_text_payload",
    "LanguageCode": ".language_code",
    "MutePayload": ".mute_payload",
    "OpenAiFunction": ".open_ai_function",
    "OpenAiFunctionParameters": ".open_ai_function_parameters",
    "OpenAiTool": ".open_ai_tool",
    "OutboundCallConfig": ".outbound_call_config",
    "OutboundCallConfigBackgroundNoise": ".outbound_call_config_background_noise",
    "OutboundCallConfigConfigurationEndpoint": ".outbound_call_config_configuration_endpoint",
    "OutboundCallConfigIntelligenceLevel": ".outbound_call_config_intelligence_level",
    "OutboundCallConfigMultilingualMode": ".outbound_call_config_multilingual_mode",
    "OutboundCallConfigPronunciationDictionaryItem": ".outbound_call_config_pronunciation_dictionary_item",
    "OutboundCallConfigToolsItem": ".outbound_call_config_tools_item",
    "OutboundCallInitiatedResponse": ".outbound_call_initiated_response",
    "OutboundDryRunResponse": ".outbound_dry_run_response",
    "OutboundNumberPool": ".outbound_number_pool",
    "Project": ".project",
    "ProjectDefaultAgent": ".project_default_agent",
    "ReadyToStartConversationPayload": ".ready_to_start_conversation_payload",
    "ReplayConversationItemResponse": ".replay_conversation_item_response",
    "ReplayConversationItemResponseResponsesItem": ".replay_conversation_item_response_responses_item",
    "ReplayToolCall": ".replay_tool_call",
    "ReplayToolCallEndpointMethod": ".replay_tool_call_endpoint_method",
    "ReplayToolCallTool": ".replay_tool_call_tool",
    "ResetPayload": ".reset_payload",
    "SayPayload": ".say_payload",
    "SetExternalIdPayload": ".set_external_id_payload",
    "SipCallError": ".sip_call_error",
    "SipCallErrorError": ".sip_call_error_error",
    "SipCallErrorErrorCode": ".sip_call_error_error_code",
    "SipOutboundCallInitiatedResponse": ".sip_outbound_call_initiated_response",
    "SipOutboundDryRunResponse": ".sip_outbound_dry_run_response",
    "Task": ".task",
    "Tool": ".tool",
    "ToolCallInterruptedPayload": ".tool_call_interrupted_payload",
    "ToolCallOutputPayload": ".tool_call_output_payload",
    "ToolCallOutputProcessedPayload": ".tool_call_output_processed_payload",
    "ToolCallOutputProcessedPayloadTool": ".tool_call_output_processed_payload_tool",
    "ToolCallPayload": ".tool_call_payload",
    "ToolDefinition": ".tool_definition",
    "ToolEndpointMethod": ".tool_endpoint_method",
    "ToolExecutionMode": ".tool_execution_mode",
    "ToolName": ".tool_name",
    "ToolParameter": ".tool_parameter",
    "ToolParameterItemType": ".tool_parameter_item_type",
    "ToolParameterLocation": ".tool_parameter_location",
    "ToolParameterType": ".tool_parameter_type",
    "ToolProject": ".tool_project",
    "ToolSpeechBeforeToolCall": ".tool_speech_before_tool_call",
    "ToolType": ".tool_type",
    "UnmutePayload": ".unmute_payload",
    "UpdateSystemPromptPayload": ".update_system_prompt_payload",
    "UpdateToolsSubsetPayload": ".update_tools_subset_payload",
    "UserFinishedSpeakingPayload": ".user_finished_speaking_payload",
    "UserStartedSpeakingPayload": ".user_started_speaking_payload",
    "ValidationError": ".validation_error",
    "ValidationErrorError": ".validation_error_error",
    "Voice": ".voice",
    "WarningPayload": ".warning_payload",
    "WarningPayloadWarning": ".warning_payload_warning",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AddSystemMessagePayload",
    "Agent",
    "AgentAudioFormat",
    "AgentBackgroundNoise",
    "AgentConfigurationEndpoint",
    "AgentIntegration",
    "AgentIntelligenceLevel",
    "AgentMultilingualMode",
    "AgentProject",
    "AgentPronunciationDictionaryItem",
    "AgentTemplateVariablesValue",
    "AgentToolsItem",
    "ApiKeyWithSecret",
    "AssistantChoseNotToRespondPayload",
    "AssistantEndedConversationPayload",
    "AssistantFinishedSpeakingPayload",
    "AssistantStartedSpeakingPayload",
    "AudioChunkPayload",
    "AudioChunkResponsePayload",
    "BadRequestErrorBody",
    "BasicError",
    "BasicErrorError",
    "BuiltInToolConfig",
    "BuiltInToolConfigSpeechBeforeToolCall",
    "BuiltInToolConfigs",
    "BuiltInToolDefinition",
    "BuiltInToolDefinitionName",
    "ConfigOptions",
    "ConfigOptionsBackgroundNoise",
    "ConfigOptionsConfigurationEndpoint",
    "ConfigOptionsDataRetentionPolicy",
    "ConfigOptionsDataRetentionPolicyAudioRecordings",
    "ConfigOptionsDataRetentionPolicyAudioRecordingsAudioRecordings",
    "ConfigOptionsDataRetentionPolicyAudioRecordingsTranscripts",
    "ConfigOptionsDataRetentionPolicyZero",
    "ConfigOptionsInputFormat",
    "ConfigOptionsIntelligenceLevel",
    "ConfigOptionsMultilingualMode",
    "ConfigOptionsOutboundNumberPool",
    "ConfigOptionsOutputFormat",
    "ConfigOptionsPronunciationDictionaryItem",
    "ConfigOptionsTasksItem",
    "ConfigPayload",
    "Conversation",
    "ConversationAgent",
    "ConversationAnalysis",
    "ConversationBackgroundNoise",
    "ConversationCallInfo",
    "ConversationCreatedPayload",
    "ConversationDeletionInfo",
    "ConversationEndedBy",
    "ConversationEval",
    "ConversationEvalPrompt",
    "ConversationEvalPromptInfo",
    "ConversationEvalResult",
    "ConversationEvaluation",
    "ConversationEvaluationResult",
    "ConversationEvaluationResultPrompt",
    "ConversationEvaluationResultResult",
    "ConversationExtraction",
    "ConversationExtractionSchema",
    "ConversationItem",
    "ConversationItemRole",
    "ConversationItemToolCallsItem",
    "ConversationItemToolCallsItemRequestBody",
    "ConversationItemToolCallsItemTool",
    "ConversationMultilingualMode",
    "ConversationOrigin",
    "ConversationProject",
    "ConversationPronunciationDictionaryItem",
    "ConversationsListResponseConversation",
    "ConversationsListResponseConversations",
    "ConversationsListResponseConversationsPagination",
    "CreateAgentRequest",
    "CreateAgentRequestAudioFormat",
    "CreateAgentRequestBackgroundNoise",
    "CreateAgentRequestConfigurationEndpoint",
    "CreateAgentRequestIntelligenceLevel",
    "CreateAgentRequestMultilingualMode",
    "CreateAgentRequestPhoneNumber",
    "CreateAgentRequestPronunciationDictionaryItem",
    "CreateAgentRequestTemplateVariablesValue",
    "CreateAgentRequestToolsItem",
    "DataRetentionPolicy",
    "DataRetentionPolicyAudioRecordings",
    "DataRetentionPolicyAudioRecordingsAudioRecordings",
    "DataRetentionPolicyAudioRecordingsTranscripts",
    "DataRetentionPolicyZero",
    "DtmfPayload",
    "Error",
    "ErrorPayload",
    "ErrorPayloadError",
    "ExtractionField",
    "ExtractionFieldType",
    "ExtractionSchema",
    "GenerateReplyPayload",
    "InlineWebSocketTool",
    "InlineWebSocketToolExecutionMode",
    "InputCancelledPayload",
    "InputTextPayload",
    "LanguageCode",
    "MutePayload",
    "OpenAiFunction",
    "OpenAiFunctionParameters",
    "OpenAiTool",
    "OutboundCallConfig",
    "OutboundCallConfigBackgroundNoise",
    "OutboundCallConfigConfigurationEndpoint",
    "OutboundCallConfigIntelligenceLevel",
    "OutboundCallConfigMultilingualMode",
    "OutboundCallConfigPronunciationDictionaryItem",
    "OutboundCallConfigToolsItem",
    "OutboundCallInitiatedResponse",
    "OutboundDryRunResponse",
    "OutboundNumberPool",
    "Project",
    "ProjectDefaultAgent",
    "ReadyToStartConversationPayload",
    "ReplayConversationItemResponse",
    "ReplayConversationItemResponseResponsesItem",
    "ReplayToolCall",
    "ReplayToolCallEndpointMethod",
    "ReplayToolCallTool",
    "ResetPayload",
    "SayPayload",
    "SetExternalIdPayload",
    "SipCallError",
    "SipCallErrorError",
    "SipCallErrorErrorCode",
    "SipOutboundCallInitiatedResponse",
    "SipOutboundDryRunResponse",
    "Task",
    "Tool",
    "ToolCallInterruptedPayload",
    "ToolCallOutputPayload",
    "ToolCallOutputProcessedPayload",
    "ToolCallOutputProcessedPayloadTool",
    "ToolCallPayload",
    "ToolDefinition",
    "ToolEndpointMethod",
    "ToolExecutionMode",
    "ToolName",
    "ToolParameter",
    "ToolParameterItemType",
    "ToolParameterLocation",
    "ToolParameterType",
    "ToolProject",
    "ToolSpeechBeforeToolCall",
    "ToolType",
    "UnmutePayload",
    "UpdateSystemPromptPayload",
    "UpdateToolsSubsetPayload",
    "UserFinishedSpeakingPayload",
    "UserStartedSpeakingPayload",
    "ValidationError",
    "ValidationErrorError",
    "Voice",
    "WarningPayload",
    "WarningPayloadWarning",
]
