# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .add_system_message_payload import AddSystemMessagePayload
    from .agent import Agent
    from .agent_audio_format import AgentAudioFormat
    from .agent_background_noise import AgentBackgroundNoise
    from .agent_configuration_endpoint import AgentConfigurationEndpoint
    from .agent_multilingual_mode import AgentMultilingualMode
    from .agent_project import AgentProject
    from .agent_template_variables_value import AgentTemplateVariablesValue
    from .agent_tools_item import AgentToolsItem
    from .assistant_chose_not_to_respond_payload import AssistantChoseNotToRespondPayload
    from .assistant_ended_conversation_payload import AssistantEndedConversationPayload
    from .assistant_finished_speaking_payload import AssistantFinishedSpeakingPayload
    from .assistant_started_speaking_payload import AssistantStartedSpeakingPayload
    from .audio_chunk_payload import AudioChunkPayload
    from .audio_chunk_response_payload import AudioChunkResponsePayload
    from .bad_request_error_body import BadRequestErrorBody
    from .basic_error import BasicError
    from .basic_error_error import BasicErrorError
    from .config_options import ConfigOptions
    from .config_options_background_noise import ConfigOptionsBackgroundNoise
    from .config_options_input_format import ConfigOptionsInputFormat
    from .config_options_multilingual_mode import ConfigOptionsMultilingualMode
    from .config_options_output_format import ConfigOptionsOutputFormat
    from .config_options_tools_item import ConfigOptionsToolsItem
    from .config_payload import ConfigPayload
    from .conversation import Conversation
    from .conversation_agent import ConversationAgent
    from .conversation_analysis import ConversationAnalysis
    from .conversation_background_noise import ConversationBackgroundNoise
    from .conversation_call_info import ConversationCallInfo
    from .conversation_created_payload import ConversationCreatedPayload
    from .conversation_ended_by import ConversationEndedBy
    from .conversation_eval import ConversationEval
    from .conversation_eval_prompt import ConversationEvalPrompt
    from .conversation_evaluation import ConversationEvaluation
    from .conversation_evaluation_result import ConversationEvaluationResult
    from .conversation_evaluation_result_prompt import ConversationEvaluationResultPrompt
    from .conversation_evaluation_result_result import ConversationEvaluationResultResult
    from .conversation_extraction import ConversationExtraction
    from .conversation_extraction_schema import ConversationExtractionSchema
    from .conversation_item import ConversationItem
    from .conversation_item_role import ConversationItemRole
    from .conversation_item_tool_calls_item import ConversationItemToolCallsItem
    from .conversation_item_tool_calls_item_request_body import ConversationItemToolCallsItemRequestBody
    from .conversation_item_tool_calls_item_tool import ConversationItemToolCallsItemTool
    from .conversation_multilingual_mode import ConversationMultilingualMode
    from .conversation_origin import ConversationOrigin
    from .conversation_project import ConversationProject
    from .create_agent_request import CreateAgentRequest
    from .create_agent_request_audio_format import CreateAgentRequestAudioFormat
    from .create_agent_request_background_noise import CreateAgentRequestBackgroundNoise
    from .create_agent_request_configuration_endpoint import CreateAgentRequestConfigurationEndpoint
    from .create_agent_request_multilingual_mode import CreateAgentRequestMultilingualMode
    from .create_agent_request_phone_number import CreateAgentRequestPhoneNumber
    from .create_agent_request_template_variables_value import CreateAgentRequestTemplateVariablesValue
    from .create_agent_request_tools_item import CreateAgentRequestToolsItem
    from .dtmf_payload import DtmfPayload
    from .error import Error
    from .error_payload import ErrorPayload
    from .error_payload_error import ErrorPayloadError
    from .extraction_field import ExtractionField
    from .extraction_field_type import ExtractionFieldType
    from .extraction_schema import ExtractionSchema
    from .generate_reply_payload import GenerateReplyPayload
    from .get_conversation_by_external_id_response import GetConversationByExternalIdResponse
    from .input_cancelled_payload import InputCancelledPayload
    from .input_text_payload import InputTextPayload
    from .language_code import LanguageCode
    from .list_conversations_response import ListConversationsResponse
    from .list_conversations_response_pagination import ListConversationsResponsePagination
    from .mute_payload import MutePayload
    from .outbound_call_config import OutboundCallConfig
    from .outbound_call_config_multilingual_mode import OutboundCallConfigMultilingualMode
    from .outbound_call_config_tools_item import OutboundCallConfigToolsItem
    from .outbound_call_initiated_response import OutboundCallInitiatedResponse
    from .outbound_dry_run_response import OutboundDryRunResponse
    from .project import Project
    from .project_default_agent import ProjectDefaultAgent
    from .ready_to_start_conversation_payload import ReadyToStartConversationPayload
    from .reset_payload import ResetPayload
    from .say_payload import SayPayload
    from .set_external_id_payload import SetExternalIdPayload
    from .sip_call_error import SipCallError
    from .sip_call_error_error import SipCallErrorError
    from .sip_call_error_error_code import SipCallErrorErrorCode
    from .sip_outbound_call_initiated_response import SipOutboundCallInitiatedResponse
    from .sip_outbound_dry_run_response import SipOutboundDryRunResponse
    from .task import Task
    from .tool import Tool
    from .tool_call_interrupted_payload import ToolCallInterruptedPayload
    from .tool_call_output_payload import ToolCallOutputPayload
    from .tool_call_output_processed_payload import ToolCallOutputProcessedPayload
    from .tool_call_output_processed_payload_tool import ToolCallOutputProcessedPayloadTool
    from .tool_call_payload import ToolCallPayload
    from .tool_endpoint_method import ToolEndpointMethod
    from .tool_execution_mode import ToolExecutionMode
    from .tool_parameter import ToolParameter
    from .tool_parameter_item_type import ToolParameterItemType
    from .tool_parameter_location import ToolParameterLocation
    from .tool_parameter_type import ToolParameterType
    from .tool_project import ToolProject
    from .tool_type import ToolType
    from .unmute_payload import UnmutePayload
    from .update_system_prompt_payload import UpdateSystemPromptPayload
    from .user_finished_speaking_payload import UserFinishedSpeakingPayload
    from .user_started_speaking_payload import UserStartedSpeakingPayload
    from .validation_error import ValidationError
    from .validation_error_error import ValidationErrorError
    from .voice import Voice
    from .warning_payload import WarningPayload
    from .warning_payload_warning import WarningPayloadWarning
_dynamic_imports: typing.Dict[str, str] = {
    "AddSystemMessagePayload": ".add_system_message_payload",
    "Agent": ".agent",
    "AgentAudioFormat": ".agent_audio_format",
    "AgentBackgroundNoise": ".agent_background_noise",
    "AgentConfigurationEndpoint": ".agent_configuration_endpoint",
    "AgentMultilingualMode": ".agent_multilingual_mode",
    "AgentProject": ".agent_project",
    "AgentTemplateVariablesValue": ".agent_template_variables_value",
    "AgentToolsItem": ".agent_tools_item",
    "AssistantChoseNotToRespondPayload": ".assistant_chose_not_to_respond_payload",
    "AssistantEndedConversationPayload": ".assistant_ended_conversation_payload",
    "AssistantFinishedSpeakingPayload": ".assistant_finished_speaking_payload",
    "AssistantStartedSpeakingPayload": ".assistant_started_speaking_payload",
    "AudioChunkPayload": ".audio_chunk_payload",
    "AudioChunkResponsePayload": ".audio_chunk_response_payload",
    "BadRequestErrorBody": ".bad_request_error_body",
    "BasicError": ".basic_error",
    "BasicErrorError": ".basic_error_error",
    "ConfigOptions": ".config_options",
    "ConfigOptionsBackgroundNoise": ".config_options_background_noise",
    "ConfigOptionsInputFormat": ".config_options_input_format",
    "ConfigOptionsMultilingualMode": ".config_options_multilingual_mode",
    "ConfigOptionsOutputFormat": ".config_options_output_format",
    "ConfigOptionsToolsItem": ".config_options_tools_item",
    "ConfigPayload": ".config_payload",
    "Conversation": ".conversation",
    "ConversationAgent": ".conversation_agent",
    "ConversationAnalysis": ".conversation_analysis",
    "ConversationBackgroundNoise": ".conversation_background_noise",
    "ConversationCallInfo": ".conversation_call_info",
    "ConversationCreatedPayload": ".conversation_created_payload",
    "ConversationEndedBy": ".conversation_ended_by",
    "ConversationEval": ".conversation_eval",
    "ConversationEvalPrompt": ".conversation_eval_prompt",
    "ConversationEvaluation": ".conversation_evaluation",
    "ConversationEvaluationResult": ".conversation_evaluation_result",
    "ConversationEvaluationResultPrompt": ".conversation_evaluation_result_prompt",
    "ConversationEvaluationResultResult": ".conversation_evaluation_result_result",
    "ConversationExtraction": ".conversation_extraction",
    "ConversationExtractionSchema": ".conversation_extraction_schema",
    "ConversationItem": ".conversation_item",
    "ConversationItemRole": ".conversation_item_role",
    "ConversationItemToolCallsItem": ".conversation_item_tool_calls_item",
    "ConversationItemToolCallsItemRequestBody": ".conversation_item_tool_calls_item_request_body",
    "ConversationItemToolCallsItemTool": ".conversation_item_tool_calls_item_tool",
    "ConversationMultilingualMode": ".conversation_multilingual_mode",
    "ConversationOrigin": ".conversation_origin",
    "ConversationProject": ".conversation_project",
    "CreateAgentRequest": ".create_agent_request",
    "CreateAgentRequestAudioFormat": ".create_agent_request_audio_format",
    "CreateAgentRequestBackgroundNoise": ".create_agent_request_background_noise",
    "CreateAgentRequestConfigurationEndpoint": ".create_agent_request_configuration_endpoint",
    "CreateAgentRequestMultilingualMode": ".create_agent_request_multilingual_mode",
    "CreateAgentRequestPhoneNumber": ".create_agent_request_phone_number",
    "CreateAgentRequestTemplateVariablesValue": ".create_agent_request_template_variables_value",
    "CreateAgentRequestToolsItem": ".create_agent_request_tools_item",
    "DtmfPayload": ".dtmf_payload",
    "Error": ".error",
    "ErrorPayload": ".error_payload",
    "ErrorPayloadError": ".error_payload_error",
    "ExtractionField": ".extraction_field",
    "ExtractionFieldType": ".extraction_field_type",
    "ExtractionSchema": ".extraction_schema",
    "GenerateReplyPayload": ".generate_reply_payload",
    "GetConversationByExternalIdResponse": ".get_conversation_by_external_id_response",
    "InputCancelledPayload": ".input_cancelled_payload",
    "InputTextPayload": ".input_text_payload",
    "LanguageCode": ".language_code",
    "ListConversationsResponse": ".list_conversations_response",
    "ListConversationsResponsePagination": ".list_conversations_response_pagination",
    "MutePayload": ".mute_payload",
    "OutboundCallConfig": ".outbound_call_config",
    "OutboundCallConfigMultilingualMode": ".outbound_call_config_multilingual_mode",
    "OutboundCallConfigToolsItem": ".outbound_call_config_tools_item",
    "OutboundCallInitiatedResponse": ".outbound_call_initiated_response",
    "OutboundDryRunResponse": ".outbound_dry_run_response",
    "Project": ".project",
    "ProjectDefaultAgent": ".project_default_agent",
    "ReadyToStartConversationPayload": ".ready_to_start_conversation_payload",
    "ResetPayload": ".reset_payload",
    "SayPayload": ".say_payload",
    "SetExternalIdPayload": ".set_external_id_payload",
    "SipCallError": ".sip_call_error",
    "SipCallErrorError": ".sip_call_error_error",
    "SipCallErrorErrorCode": ".sip_call_error_error_code",
    "SipOutboundCallInitiatedResponse": ".sip_outbound_call_initiated_response",
    "SipOutboundDryRunResponse": ".sip_outbound_dry_run_response",
    "Task": ".task",
    "Tool": ".tool",
    "ToolCallInterruptedPayload": ".tool_call_interrupted_payload",
    "ToolCallOutputPayload": ".tool_call_output_payload",
    "ToolCallOutputProcessedPayload": ".tool_call_output_processed_payload",
    "ToolCallOutputProcessedPayloadTool": ".tool_call_output_processed_payload_tool",
    "ToolCallPayload": ".tool_call_payload",
    "ToolEndpointMethod": ".tool_endpoint_method",
    "ToolExecutionMode": ".tool_execution_mode",
    "ToolParameter": ".tool_parameter",
    "ToolParameterItemType": ".tool_parameter_item_type",
    "ToolParameterLocation": ".tool_parameter_location",
    "ToolParameterType": ".tool_parameter_type",
    "ToolProject": ".tool_project",
    "ToolType": ".tool_type",
    "UnmutePayload": ".unmute_payload",
    "UpdateSystemPromptPayload": ".update_system_prompt_payload",
    "UserFinishedSpeakingPayload": ".user_finished_speaking_payload",
    "UserStartedSpeakingPayload": ".user_started_speaking_payload",
    "ValidationError": ".validation_error",
    "ValidationErrorError": ".validation_error_error",
    "Voice": ".voice",
    "WarningPayload": ".warning_payload",
    "WarningPayloadWarning": ".warning_payload_warning",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AddSystemMessagePayload",
    "Agent",
    "AgentAudioFormat",
    "AgentBackgroundNoise",
    "AgentConfigurationEndpoint",
    "AgentMultilingualMode",
    "AgentProject",
    "AgentTemplateVariablesValue",
    "AgentToolsItem",
    "AssistantChoseNotToRespondPayload",
    "AssistantEndedConversationPayload",
    "AssistantFinishedSpeakingPayload",
    "AssistantStartedSpeakingPayload",
    "AudioChunkPayload",
    "AudioChunkResponsePayload",
    "BadRequestErrorBody",
    "BasicError",
    "BasicErrorError",
    "ConfigOptions",
    "ConfigOptionsBackgroundNoise",
    "ConfigOptionsInputFormat",
    "ConfigOptionsMultilingualMode",
    "ConfigOptionsOutputFormat",
    "ConfigOptionsToolsItem",
    "ConfigPayload",
    "Conversation",
    "ConversationAgent",
    "ConversationAnalysis",
    "ConversationBackgroundNoise",
    "ConversationCallInfo",
    "ConversationCreatedPayload",
    "ConversationEndedBy",
    "ConversationEval",
    "ConversationEvalPrompt",
    "ConversationEvaluation",
    "ConversationEvaluationResult",
    "ConversationEvaluationResultPrompt",
    "ConversationEvaluationResultResult",
    "ConversationExtraction",
    "ConversationExtractionSchema",
    "ConversationItem",
    "ConversationItemRole",
    "ConversationItemToolCallsItem",
    "ConversationItemToolCallsItemRequestBody",
    "ConversationItemToolCallsItemTool",
    "ConversationMultilingualMode",
    "ConversationOrigin",
    "ConversationProject",
    "CreateAgentRequest",
    "CreateAgentRequestAudioFormat",
    "CreateAgentRequestBackgroundNoise",
    "CreateAgentRequestConfigurationEndpoint",
    "CreateAgentRequestMultilingualMode",
    "CreateAgentRequestPhoneNumber",
    "CreateAgentRequestTemplateVariablesValue",
    "CreateAgentRequestToolsItem",
    "DtmfPayload",
    "Error",
    "ErrorPayload",
    "ErrorPayloadError",
    "ExtractionField",
    "ExtractionFieldType",
    "ExtractionSchema",
    "GenerateReplyPayload",
    "GetConversationByExternalIdResponse",
    "InputCancelledPayload",
    "InputTextPayload",
    "LanguageCode",
    "ListConversationsResponse",
    "ListConversationsResponsePagination",
    "MutePayload",
    "OutboundCallConfig",
    "OutboundCallConfigMultilingualMode",
    "OutboundCallConfigToolsItem",
    "OutboundCallInitiatedResponse",
    "OutboundDryRunResponse",
    "Project",
    "ProjectDefaultAgent",
    "ReadyToStartConversationPayload",
    "ResetPayload",
    "SayPayload",
    "SetExternalIdPayload",
    "SipCallError",
    "SipCallErrorError",
    "SipCallErrorErrorCode",
    "SipOutboundCallInitiatedResponse",
    "SipOutboundDryRunResponse",
    "Task",
    "Tool",
    "ToolCallInterruptedPayload",
    "ToolCallOutputPayload",
    "ToolCallOutputProcessedPayload",
    "ToolCallOutputProcessedPayloadTool",
    "ToolCallPayload",
    "ToolEndpointMethod",
    "ToolExecutionMode",
    "ToolParameter",
    "ToolParameterItemType",
    "ToolParameterLocation",
    "ToolParameterType",
    "ToolProject",
    "ToolType",
    "UnmutePayload",
    "UpdateSystemPromptPayload",
    "UserFinishedSpeakingPayload",
    "UserStartedSpeakingPayload",
    "ValidationError",
    "ValidationErrorError",
    "Voice",
    "WarningPayload",
    "WarningPayloadWarning",
]
