# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class AgentIntegration(UncheckedBaseModel):
    """
    A third-party integration enabled for an agent.
    """

    account_id: str = pydantic.Field()
    """
    The connected account ID.
    """

    account_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The connected account name.
    """

    action_names: typing.List[str] = pydantic.Field()
    """
    The integration actions available to the agent.
    """

    app_slug: str = pydantic.Field()
    """
    The slug identifying the integration app.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
