# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class ApiKeyWithSecret(UncheckedBaseModel):
    id: str = pydantic.Field()
    """
    The API key ID.
    """

    name: str = pydantic.Field()
    """
    The name of the API key.
    """

    api_key: str = pydantic.Field()
    """
    The API key secret. Only returned once, when the key is created or rotated.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
