# This file was auto-generated by Fern from our API Definition.

import typing

from .basic_error import BasicError
from .sip_call_error import SipCallError
from .validation_error import ValidationError

BadRequestErrorBody = typing.Union[ValidationError, BasicError, SipCallError]
