# This file was auto-generated by Fern from our API Definition.

import typing

BuiltInToolDefinitionName = typing.Union[
    typing.Literal["keypad_input", "natural_conversation_ending", "choose_not_to_respond"], typing.Any
]
