# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .config_options_background_noise import ConfigOptionsBackgroundNoise
from .config_options_input_format import ConfigOptionsInputFormat
from .config_options_multilingual_mode import ConfigOptionsMultilingualMode
from .config_options_output_format import ConfigOptionsOutputFormat
from .config_options_tools_item import ConfigOptionsToolsItem


class ConfigOptions(UncheckedBaseModel):
    """
    Configuration fields for the initial `config` message.
    """

    agent: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent name to use for conversation
    """

    project: typing.Optional[str] = pydantic.Field(default=None)
    """
    Project name
    """

    model: typing.Optional[typing.Literal["merritt"]] = pydantic.Field(default=None)
    """
    STS model to use
    """

    system_prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    System prompt for AI assistant
    """

    audio_speed: typing.Optional[float] = pydantic.Field(default=None)
    """
    Audio playback speed
    """

    background_noise_level: typing.Optional[float] = pydantic.Field(default=None)
    """
    Background noise level for the conversation
    """

    background_noise: typing.Optional[ConfigOptionsBackgroundNoise] = pydantic.Field(default=None)
    """
    Background noise type for the conversation
    """

    generate_welcome_message: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When `true`, the welcome message will be automatically generated and the `welcome_message` field will be ignored.
    """

    welcome_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Message to play when conversation starts. Ignored when `generate_welcome_message` is `true`.
    """

    voice_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Voice ID to use for speech synthesis
    """

    input_format: typing.Optional[ConfigOptionsInputFormat] = pydantic.Field(default=None)
    """
    Audio input format
    """

    output_format: typing.Optional[ConfigOptionsOutputFormat] = pydantic.Field(default=None)
    """
    Audio output format
    """

    vad_prebuffer_duration_ms: typing.Optional[float] = pydantic.Field(default=None)
    """
    Voice activity detection prebuffer duration
    """

    vad_min_speech_duration_ms: typing.Optional[float] = pydantic.Field(default=None)
    """
    Minimum speech duration for VAD
    """

    vad_min_silence_duration_ms: typing.Optional[float] = pydantic.Field(default=None)
    """
    Minimum silence duration for VAD
    """

    vad_threshold: typing.Optional[float] = pydantic.Field(default=None)
    """
    Voice activity detection threshold
    """

    min_words_to_interrupt: typing.Optional[float] = pydantic.Field(default=None)
    """
    Minimum number of words required to interrupt the assistant.
    """

    generate_no_input_poke_text: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to have the no-input poke text be generated by AI
    """

    no_input_poke_sec: typing.Optional[float] = pydantic.Field(default=None)
    """
    Seconds of silence before poke message
    """

    no_input_poke_text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Poke message text. Ignored when generate_no_input_poke_text is true.
    """

    no_input_end_conversation_sec: typing.Optional[float] = pydantic.Field(default=None)
    """
    Seconds of silence before ending conversation
    """

    default_language: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 639-1 language code that sets the agent's default language to recognize and speak. Welcome message and no input poke text should be in this language.
    """

    additional_languages: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Array of additional ISO 639-1 language codes that the agent should be able to recognize and speak. Should not include `default_language`.
    """

    multilingual_mode: typing.Optional[ConfigOptionsMultilingualMode] = pydantic.Field(default=None)
    """
    If `"auto"`, each user audio is automatically identified for the language to respond in. If `"request"`, user must request to change language (recommended).
    """

    boosted_keywords: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Keywords to boost in speech recognition
    """

    tools: typing.Optional[typing.List[ConfigOptionsToolsItem]] = pydantic.Field(default=None)
    """
    Names of tools available to the assistant.
    """

    template_variables: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Template variables for system prompt and welcome message
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
