# This file was auto-generated by Fern from our API Definition.

import typing

from .config_options_data_retention_policy_audio_recordings import ConfigOptionsDataRetentionPolicyAudioRecordings
from .config_options_data_retention_policy_zero import ConfigOptionsDataRetentionPolicyZero

ConfigOptionsDataRetentionPolicy = typing.Union[
    ConfigOptionsDataRetentionPolicyZero, ConfigOptionsDataRetentionPolicyAudioRecordings
]
