# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .conversation_item import ConversationItem
from .conversation_project import ConversationProject


class Conversation(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The conversation ID.
    """

    external_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    External ID for conversation tracking.
    """

    project: ConversationProject
    model: str = pydantic.Field()
    """
    The STS model used.
    """

    welcome_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Welcome message played at start.
    """

    template_variables: typing.Dict[str, str] = pydantic.Field()
    """
    Template variables used in the conversation.
    """

    input_format: str = pydantic.Field()
    """
    Audio input format.
    """

    output_format: str = pydantic.Field()
    """
    Audio output format.
    """

    live_transcript: str = pydantic.Field()
    """
    Live transcript of the conversation.
    """

    post_call_transcript: typing.Optional[str] = pydantic.Field(default=None)
    """
    Post-call processed transcript.
    """

    duration_ms: int = pydantic.Field()
    """
    Duration of the conversation in milliseconds.
    """

    started_at: dt.datetime = pydantic.Field()
    """
    When the conversation started.
    """

    ended_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the conversation ended.
    """

    audio_url: str = pydantic.Field()
    """
    URL to the conversation audio file.
    """

    items: typing.List[ConversationItem] = pydantic.Field()
    """
    Array of conversation items (turns).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
