# This file was auto-generated by Fern from our API Definition.

import typing

ConversationOrigin = typing.Union[
    typing.Literal[
        "web",
        "web-playground",
        "web-demo",
        "direct",
        "livekit-agents-py",
        "livekit-agents-js",
        "sdk-py",
        "sdk-js",
        "inbound",
        "telephony-inbound",
        "outbound",
        "telephony-outbound",
        "replay",
    ],
    typing.Any,
]
