# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreateCodecRequest(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    The codec name. Cannot contain a slash (/).
    """

    latent_sample_rate: float = pydantic.Field()
    """
    Latent sample rate (must be positive).
    """

    waveform_sample_rate: float = pydantic.Field()
    """
    Waveform sample rate (must be positive).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
