# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .data_retention_policy_audio_recordings_audio_recordings import DataRetentionPolicyAudioRecordingsAudioRecordings
from .data_retention_policy_audio_recordings_transcripts import DataRetentionPolicyAudioRecordingsTranscripts


class DataRetentionPolicyAudioRecordings(UncheckedBaseModel):
    """
    Standard data retention with configurable deletion windows.
    """

    zero_data_retention: typing.Literal[False] = pydantic.Field(default=False)
    """
    Must be `false` for standard data retention.
    """

    transcripts: DataRetentionPolicyAudioRecordingsTranscripts
    audio_recordings: DataRetentionPolicyAudioRecordingsAudioRecordings

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
