# This file was auto-generated by Fern from our API Definition.

import typing

from .data_retention_policy_audio_recordings import DataRetentionPolicyAudioRecordings
from .data_retention_policy_zero import DataRetentionPolicyZero

DataRetentionPolicy = typing.Union[DataRetentionPolicyZero, DataRetentionPolicyAudioRecordings]
