# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .external_storage_policy_addressing_style import ExternalStoragePolicyAddressingStyle


class ExternalStoragePolicy(UncheckedBaseModel):
    """
    An S3-compatible destination that conversation artifacts are delivered to.
    """

    id: str = pydantic.Field()
    """
    The ID of the external storage policy.
    """

    name: str = pydantic.Field()
    """
    The name of the external storage policy. Agents reference the policy by this name.
    """

    endpoint_url: str = pydantic.Field()
    """
    The S3-compatible endpoint URL that artifacts are uploaded to.
    """

    bucket: str = pydantic.Field()
    """
    The bucket that artifacts are uploaded to.
    """

    region: typing.Optional[str] = pydantic.Field(default=None)
    """
    The region of the bucket. `null` when the endpoint doesn't require a region.
    """

    key_prefix: typing.Optional[str] = pydantic.Field(default=None)
    """
    Prefix prepended to every object key. `null` when objects are written at the bucket root.
    """

    addressing_style: ExternalStoragePolicyAddressingStyle = pydantic.Field()
    """
    How bucket names are addressed in requests to the endpoint.
    """

    agent_count: int = pydantic.Field()
    """
    Number of agents currently referencing this external storage policy.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
