# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .generated_tool_call import GeneratedToolCall


class GeneratedResponse(UncheckedBaseModel):
    text: str = pydantic.Field()
    """
    The text the assistant would say. Empty when the response only makes tool calls.
    """

    tool_calls: typing.List[GeneratedToolCall] = pydantic.Field()
    """
    Tool calls the assistant would make - note that the tools are not actually called.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
