# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class GeneratedToolCall(UncheckedBaseModel):
    tool_call_id: str = pydantic.Field()
    """
    Identifier for this tool call. Send it back as the `tool_call_id` of the matching `tool_call_output` input item.
    """

    tool_name: str = pydantic.Field()
    """
    Name of the tool to call. Always one of the `tool_definitions` from the request.
    """

    request_body: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Arguments the assistant produced for the request body.
    """

    query_params: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Arguments the assistant produced as query parameters.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
