# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .inline_web_socket_tool_execution_mode import InlineWebSocketToolExecutionMode
from .open_ai_tool import OpenAiTool


class InlineWebSocketTool(UncheckedBaseModel):
    """
    Inline WebSocket tool definition for this conversation. Inline tools are not persisted to your workspace; they are executed by your connected WebSocket application when Phonic sends a `tool_call` message.
    """

    type: typing.Literal["custom_websocket"] = "custom_websocket"
    tool_schema: OpenAiTool
    execution_mode: typing.Optional[InlineWebSocketToolExecutionMode] = pydantic.Field(default=None)
    """
    Whether the assistant waits for the tool output before continuing.
    """

    tool_call_output_timeout_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Timeout in milliseconds for the client to send a `tool_call_output` message.
    """

    require_speech_before_tool_call: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, forces the assistant to speak before executing the tool.
    """

    wait_for_speech_before_tool_call: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, waits for the assistant's speech to finish before sending the tool call.
    """

    forbid_speech_after_tool_call: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, prevents the assistant from speaking after executing the tool.
    """

    allow_tool_chaining: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, allows the assistant to call another tool after this tool.
    """

    wait_for_response: typing.Optional[bool] = pydantic.Field(default=None)
    """
    For async tools, when true, the assistant waits for the response and speaks when it arrives.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
