# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .open_ai_function_parameters import OpenAiFunctionParameters


class OpenAiFunction(UncheckedBaseModel):
    name: str = pydantic.Field()
    """
    Function name the assistant will use in `tool_call.tool_name`.
    """

    description: str = pydantic.Field()
    """
    Description of what the tool does and when to call it.
    """

    parameters: OpenAiFunctionParameters
    strict: typing.Literal[True] = pydantic.Field(default=True)
    """
    Inline tools require strict function calling.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
