# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class OutboundNumberPool(UncheckedBaseModel):
    """
    Pool of phone numbers used for outbound calls.
    """

    active: typing.List[str] = pydantic.Field()
    """
    E.164 formatted phone numbers available for outbound calls.
    """

    blocked: typing.List[str] = pydantic.Field()
    """
    E.164 formatted phone numbers that are blocked from being used.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
