# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .replay_tool_call import ReplayToolCall


class ReplayConversationItemResponseResponsesItem(UncheckedBaseModel):
    text: str = pydantic.Field()
    """
    The text the LLM produced for this replay response.
    """

    tool_calls: typing.List[ReplayToolCall] = pydantic.Field()
    """
    Tool calls the LLM would invoke for this replay response - note that the tools will not actually be called during replay.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
