# This file was auto-generated by Fern from our API Definition.

import typing

from .responses_assistant_message import ResponsesAssistantMessage
from .responses_tool_call_output import ResponsesToolCallOutput
from .responses_user_message import ResponsesUserMessage

ResponsesInputItem = typing.Union[ResponsesUserMessage, ResponsesAssistantMessage, ResponsesToolCallOutput]
