# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .responses_tool_call import ResponsesToolCall


class ResponsesAssistantMessage(UncheckedBaseModel):
    """
    An assistant turn. Must carry `text`, `tool_calls`, or both.
    """

    role: typing.Literal["assistant"] = "assistant"
    text: str = pydantic.Field()
    """
    What the assistant said. Empty when the turn only made tool calls.
    """

    tool_calls: typing.Optional[typing.List[ResponsesToolCall]] = pydantic.Field(default=None)
    """
    Tool calls the assistant made on this turn. Each one must be followed immediately by its matching `tool_call_output` item.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
