# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class ResponsesTransferToAgentAction(UncheckedBaseModel):
    """
    The assistant transferred the conversation to another agent (a `built_in_transfer_to_agent` tool).
    """

    agent: str = pydantic.Field()
    """
    Name of the agent the conversation would be transferred to.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
