# This file was auto-generated by Fern from our API Definition.

import typing

ResponsesTransferToPhoneNumberActionOnTransferNoAnswer = typing.Union[
    typing.Literal["return_to_assistant", "keep_retrying"], typing.Any
]
