# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .responses_built_in_tool_name import ResponsesBuiltInToolName
from .responses_built_in_tool_tool_config import ResponsesBuiltInToolToolConfig


class ResponsesBuiltInTool(UncheckedBaseModel):
    """
    A built-in tool with an explicit configuration, as an alternative to referencing it by bare name (which uses the tool's default configuration). `keypad_input` and `natural_conversation_ending` take a `speech_before_tool_call` config; `choose_not_to_respond` takes a `respond_after_sec` config.
    """

    type: typing.Literal["built_in"] = "built_in"
    name: ResponsesBuiltInToolName = pydantic.Field()
    """
    The name of the built-in tool.
    """

    tool_config: ResponsesBuiltInToolToolConfig = pydantic.Field()
    """
    The tool's configuration. Use `BuiltInToolConfig` for `keypad_input` and `natural_conversation_ending`, or `ChooseNotToRespondToolConfig` for `choose_not_to_respond`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
