# This file was auto-generated by Fern from our API Definition.

import typing

from .responses_built_in_tool import ResponsesBuiltInTool
from .responses_tool_name import ResponsesToolName

ResponsesTool = typing.Union[ResponsesToolName, ResponsesBuiltInTool]
