# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .responses_transfer_to_phone_number_action_on_transfer_no_answer import (
    ResponsesTransferToPhoneNumberActionOnTransferNoAnswer,
)


class ResponsesTransferToPhoneNumberAction(UncheckedBaseModel):
    """
    The assistant transferred the call to a phone number (a `built_in_transfer_to_phone_number` tool).
    """

    phone_number: str = pydantic.Field()
    """
    The phone number the call would be transferred to, in E.164 format.
    """

    detect_voicemail: bool = pydantic.Field()
    """
    Whether Phonic would detect whether the transfer reached a voicemail.
    """

    use_agent_phone_number: bool = pydantic.Field()
    """
    Whether the transfer would be placed from the agent's phone number.
    """

    keep_listening: bool = pydantic.Field()
    """
    Whether Phonic would keep transcribing the call after the transfer.
    """

    on_transfer_no_answer: ResponsesTransferToPhoneNumberActionOnTransferNoAnswer = pydantic.Field()
    """
    What Phonic would do if the transfer target does not answer. `return_to_assistant` hands control back to the agent; `keep_retrying` re-dials the target.
    """

    dtmf: typing.Optional[str] = pydantic.Field(default=None)
    """
    Digits to dial after the transfer connects, for navigating a phone menu. Null when there are none.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
