# This file was auto-generated by Fern from our API Definition.

import typing

SipCallErrorErrorCode = typing.Union[
    typing.Literal["sip_call_failed", "sip_auth_failed", "invalid_phone_number"], typing.Any
]
