# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class SipOutboundCallInitiatedResponse(UncheckedBaseModel):
    conversation_id: str = pydantic.Field()
    """
    The ID of the created conversation.
    """

    twilio_call_sid: str = pydantic.Field()
    """
    The Twilio Call SID.
    """

    dry_run: typing.Literal[False] = pydantic.Field(default=False)
    """
    Always false when a call was placed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
