# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .sip_call_error_error_code import SipCallErrorErrorCode


class SipCallErrorError(UncheckedBaseModel):
    message: str = pydantic.Field()
    """
    Human-readable error message.
    """

    code: SipCallErrorErrorCode = pydantic.Field()
    """
    Machine-readable error code.
    """

    sip_status_code: int = pydantic.Field()
    """
    The SIP response status code from the carrier (e.g. 403, 486, 603).
    """

    sip_status: str = pydantic.Field()
    """
    The SIP response reason phrase from the carrier (e.g. "Network Blocked", "Trunk CPS limit exceeded").
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
