# This file was auto-generated by Fern from our API Definition.

import typing

from .tool_parameter import ToolParameter
from .tool_parameters_json_schema import ToolParametersJsonSchema

ToolParameters = typing.Union[typing.List[ToolParameter], ToolParametersJsonSchema]
