# This file was auto-generated by Fern from our API Definition.

import typing

from .built_in_tool_definition import BuiltInToolDefinition
from .inline_web_socket_tool import InlineWebSocketTool
from .tool_name import ToolName

ToolDefinition = typing.Union[ToolName, BuiltInToolDefinition, InlineWebSocketTool]
