# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .tool_endpoint_method import ToolEndpointMethod
from .tool_execution_mode import ToolExecutionMode
from .tool_parameter_locations_value import ToolParameterLocationsValue
from .tool_parameters import ToolParameters
from .tool_project import ToolProject
from .tool_speech_before_tool_call import ToolSpeechBeforeToolCall
from .tool_type import ToolType


class Tool(UncheckedBaseModel):
    id: str = pydantic.Field()
    """
    The ID of the tool.
    """

    name: str = pydantic.Field()
    """
    The name of the tool.
    """

    description: str = pydantic.Field()
    """
    Description of what the tool does.
    """

    project: ToolProject
    type: ToolType = pydantic.Field()
    """
    The type of tool.
    """

    execution_mode: typing.Optional[ToolExecutionMode] = pydantic.Field(default=None)
    """
    Mode of operation - sync waits for response, async continues without waiting.
    """

    parameters: ToolParameters = pydantic.Field()
    """
    The tool's parameters, returned in the same form they were defined in.
    Tools defined with a flat list of parameters return an array of parameter definitions (with `location` included inline for `custom_webhook` tools).
    Tools defined with a raw JSON Schema object return that object; for `custom_webhook` tools the parameter placement is then returned separately in `parameter_locations`.
    """

    parameter_locations: typing.Optional[typing.Dict[str, ToolParameterLocationsValue]] = pydantic.Field(default=None)
    """
    Where each top-level parameter is sent in the webhook request, as a map from parameter name to location.
    Only returned for `custom_webhook` tools whose `parameters` are a raw JSON Schema object. Tools defined with a flat list of parameters carry `location` inline on each parameter instead.
    """

    endpoint_method: typing.Optional[ToolEndpointMethod] = pydantic.Field(default=None)
    """
    HTTP method for webhook tools.
    """

    endpoint_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL for webhook tools.
    """

    endpoint_headers: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Headers for webhook tools.
    """

    endpoint_timeout_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Timeout in milliseconds for webhook tools.
    """

    tool_call_output_timeout_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Timeout in milliseconds for WebSocket tool responses.
    """

    phone_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    The E.164 formatted phone number to transfer calls to. Set to null if the agent should determine the phone number.
    """

    dtmf: typing.Optional[str] = pydantic.Field(default=None)
    """
    DTMF digits to send after the transfer connects (e.g., "1234"). Defaults to null. Ignored when dynamic_dtmf is true.
    """

    post_transfer_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Fixed line the agent speaks into the bridged call once the transfer connects. Defaults to null, meaning no announcement. Always null when keep_listening is false. Only returned for built_in_transfer_to_phone_number tools.
    """

    dynamic_dtmf: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, the agent determines the DTMF digits at call time (and may choose to send none); the static dtmf is ignored. Only sent when use_agent_phone_number is true (not on a SIP REFER transfer).
    """

    use_agent_phone_number: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, Phonic will transfer the call using the agent's phone number. When false, Phonic will transfer the call using the phone number of the party to whom the agent is connected. This is only available for built_in_transfer_to_phone_number tools.
    """

    detect_voicemail: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, Phonic will listen in and tell the user if the transfer hits voicemail. This is only available for built_in_transfer_to_phone_number tools when use_agent_phone_number is true.
    """

    keep_listening: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, Phonic bridges the transfer and stays on the call. When false, the call is handed off with a SIP REFER and Phonic drops out, so use_agent_phone_number, detect_voicemail and dynamic_dtmf are false and dtmf and post_transfer_message are null. Only returned for built_in_transfer_to_phone_number tools.
    """

    agents_to_transfer_to: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Array of agent names that the LLM can choose from when transferring. Required for built_in_transfer_to_agent tools.
    """

    require_speech_before_tool_call: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, forces the agent to speak before executing the tool.
    """

    speech_before_tool_call: typing.Optional[ToolSpeechBeforeToolCall] = pydantic.Field(default=None)
    """
    For built_in_natural_conversation_ending and built_in_keypad_input tools. Whether the agent must speak before calling the tool ("required"), the model decides ("optional"), or the agent must stay silent ("suppressed"). Not used by other tool types.
    """

    respond_after_sec: typing.Optional[float] = pydantic.Field(default=None)
    """
    For built_in_choose_not_to_respond tools. Number of seconds to wait after the tool fires before the agent speaks a follow-up if the user stays silent. When null, the agent stays silent (default). Not used by other tool types.
    """

    wait_for_speech_before_tool_call: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If true, the agent will wait to finish speaking before executing the tool. This is only available for custom_webhook and custom_websocket tools.
    """

    forbid_speech_after_tool_call: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, forbids the agent from speaking after executing the tool. Available for custom_context, custom_webhook and custom_websocket tools.
    """

    forbid_tool_call_after_speech: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, forbids the agent from calling the tool right after it has spoken. Available for custom_webhook and custom_websocket tools.
    """

    allow_tool_chaining: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, allows the agent to chain and execute other tools after executing the tool. Available for custom_context, custom_webhook and custom_websocket tools.
    """

    wait_for_response: typing.Optional[bool] = pydantic.Field(default=None)
    """
    The agent doesn't typically wait for the response of async tools. When true, makes the agent wait for a response, not call other tools and inform the user of the result. Only returned for custom_webhook and custom_websocket tools.
    """

    context: typing.Optional[str] = pydantic.Field(default=None)
    """
    The static context returned to the agent. Only present for custom_context tools.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
