# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class ToolParametersJsonSchema(UncheckedBaseModel):
    """
    A tool's parameters expressed as a raw JSON Schema object, for parameters that the flat `ToolParameter` list cannot express: nested objects, arrays of objects, `anyOf` variants, `null`, and non-string enums.
    Each entry in `properties` is a JSON Schema value supporting `type` (`"string"`, `"integer"`, `"number"`, `"boolean"`, `"null"`, `"array"`, `"object"`), `description`, `enum` (string parameters only), `items` (for arrays), `properties`/`required`/`additionalProperties` (for objects) and `anyOf`. Values may be nested up to 5 levels deep.
    Parameter names cannot be any of the reserved names that Phonic injects into every tool call: `call_info`, `conversation_id`, `from_phone_number`, `to_phone_number`, `twilio_call_sid`.
    For `custom_webhook` tools, parameter placement is supplied separately in `parameter_locations` rather than inline on the schema.
    """

    type: typing.Literal["object"] = "object"
    properties: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    The tool's top-level parameters, as a map from parameter name to its JSON Schema.
    """

    required: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The names of the required top-level parameters. Every name must be defined in `properties`.
    """

    additional_properties: typing_extensions.Annotated[
        typing.Optional[typing.Literal[False]],
        FieldMetadata(alias="additionalProperties"),
        pydantic.Field(
            alias="additionalProperties",
            description="Must be `false`. Tool parameter schemas do not allow properties beyond the ones declared.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
