# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class WorkspaceGetResponse(UncheckedBaseModel):
    active_conversations: int = pydantic.Field()
    """
    Number of conversations currently in progress for this workspace.
    """

    max_active_conversations: int = pydantic.Field()
    """
    Maximum number of concurrent conversations allowed for this workspace.
    """

    logo_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL of the workspace logo (PNG or SVG), or null if not set.
    """

    invite_link_allowed_domains: typing.List[str] = pydantic.Field()
    """
    Email domains allowed to join the workspace via invite link.
    """

    ip_allowlist: typing.List[str] = pydantic.Field()
    """
    IP addresses or CIDR ranges allowed to access the workspace.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
