# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.unchecked_base_model import construct_type
from ..errors.bad_gateway_error import BadGatewayError
from ..errors.bad_request_error import BadRequestError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..requests.responses_input_item import ResponsesInputItemParams
from ..requests.responses_tool_definition import ResponsesToolDefinitionParams
from ..types.basic_error import BasicError
from ..types.generate_responses_response import GenerateResponsesResponse
from ..types.language_code import LanguageCode
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawResponsesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(
        self,
        *,
        system_prompt: str,
        input: typing.Sequence[ResponsesInputItemParams],
        voice_id: typing.Optional[str] = OMIT,
        default_language: typing.Optional[LanguageCode] = OMIT,
        additional_languages: typing.Optional[typing.Sequence[LanguageCode]] = OMIT,
        tool_definitions: typing.Optional[typing.Sequence[ResponsesToolDefinitionParams]] = OMIT,
        num_responses: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GenerateResponsesResponse]:
        """
        Generates one or more alternative assistant responses for a conversation
        you supply inline to simulate Phonic agent behavior.

        This endpoint is stateless, so it does not create a new conversation or
        store anything. The request carries the system prompt, a conversation so
        far as `input`, and the tools the assistant may call as
        `tool_definitions`.

        Each item in `input` is a user message, an assistant message (with
        optional `tool_calls`), or a `tool_call_output`. Every assistant tool
        call must be followed immediately by the `tool_call_output` item that
        carries its result.

        This is an experimental feature and must be enabled for your workspace;
        otherwise, it returns `404`. Please contact our team if you would like
        access.

        Parameters
        ----------
        system_prompt : str
            The system prompt the assistant should follow.

        input : typing.Sequence[ResponsesInputItemParams]
            The conversation so far, in order. Must contain at least one item.

        voice_id : typing.Optional[str]
            ID of the voice the assistant would speak with. It shapes how the responses are worded.

        default_language : typing.Optional[LanguageCode]
            ISO 639-1 language code that sets the assistant's default language to recognize and speak.

        additional_languages : typing.Optional[typing.Sequence[LanguageCode]]
            Array of additional ISO 639-1 language codes that the assistant should be able to recognize and speak. Should not include `default_language`.

        tool_definitions : typing.Optional[typing.Sequence[ResponsesToolDefinitionParams]]
            The tools the assistant may call, defined inline. Names must be unique and cannot be one of the names Phonic reserves for its built-in tools.

        num_responses : typing.Optional[int]
            Number of alternative responses to generate.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GenerateResponsesResponse]
            Success response
        """
        _response = self._client_wrapper.httpx_client.request(
            "responses",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "system_prompt": system_prompt,
                "voice_id": voice_id,
                "default_language": default_language,
                "additional_languages": additional_languages,
                "input": convert_and_respect_annotation_metadata(
                    object_=input, annotation=typing.Sequence[ResponsesInputItemParams], direction="write"
                ),
                "tool_definitions": convert_and_respect_annotation_metadata(
                    object_=tool_definitions,
                    annotation=typing.Sequence[ResponsesToolDefinitionParams],
                    direction="write",
                ),
                "num_responses": num_responses,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GenerateResponsesResponse,
                    construct_type(
                        type_=GenerateResponsesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawResponsesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self,
        *,
        system_prompt: str,
        input: typing.Sequence[ResponsesInputItemParams],
        voice_id: typing.Optional[str] = OMIT,
        default_language: typing.Optional[LanguageCode] = OMIT,
        additional_languages: typing.Optional[typing.Sequence[LanguageCode]] = OMIT,
        tool_definitions: typing.Optional[typing.Sequence[ResponsesToolDefinitionParams]] = OMIT,
        num_responses: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GenerateResponsesResponse]:
        """
        Generates one or more alternative assistant responses for a conversation
        you supply inline to simulate Phonic agent behavior.

        This endpoint is stateless, so it does not create a new conversation or
        store anything. The request carries the system prompt, a conversation so
        far as `input`, and the tools the assistant may call as
        `tool_definitions`.

        Each item in `input` is a user message, an assistant message (with
        optional `tool_calls`), or a `tool_call_output`. Every assistant tool
        call must be followed immediately by the `tool_call_output` item that
        carries its result.

        This is an experimental feature and must be enabled for your workspace;
        otherwise, it returns `404`. Please contact our team if you would like
        access.

        Parameters
        ----------
        system_prompt : str
            The system prompt the assistant should follow.

        input : typing.Sequence[ResponsesInputItemParams]
            The conversation so far, in order. Must contain at least one item.

        voice_id : typing.Optional[str]
            ID of the voice the assistant would speak with. It shapes how the responses are worded.

        default_language : typing.Optional[LanguageCode]
            ISO 639-1 language code that sets the assistant's default language to recognize and speak.

        additional_languages : typing.Optional[typing.Sequence[LanguageCode]]
            Array of additional ISO 639-1 language codes that the assistant should be able to recognize and speak. Should not include `default_language`.

        tool_definitions : typing.Optional[typing.Sequence[ResponsesToolDefinitionParams]]
            The tools the assistant may call, defined inline. Names must be unique and cannot be one of the names Phonic reserves for its built-in tools.

        num_responses : typing.Optional[int]
            Number of alternative responses to generate.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GenerateResponsesResponse]
            Success response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "responses",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            json={
                "system_prompt": system_prompt,
                "voice_id": voice_id,
                "default_language": default_language,
                "additional_languages": additional_languages,
                "input": convert_and_respect_annotation_metadata(
                    object_=input, annotation=typing.Sequence[ResponsesInputItemParams], direction="write"
                ),
                "tool_definitions": convert_and_respect_annotation_metadata(
                    object_=tool_definitions,
                    annotation=typing.Sequence[ResponsesToolDefinitionParams],
                    direction="write",
                ),
                "num_responses": num_responses,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GenerateResponsesResponse,
                    construct_type(
                        type_=GenerateResponsesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
