# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AuthCreateSessionTokenResponse(UniversalBaseModel):
    session_token: str = pydantic.Field()
    """
    The session token to use for authentication.
    """

    expires_at: dt.datetime = pydantic.Field()
    """
    When the session token expires.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
