# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .add_system_message_payload import AddSystemMessagePayloadParams
    from .agent import AgentParams
    from .agent_configuration_endpoint import AgentConfigurationEndpointParams
    from .agent_integration import AgentIntegrationParams
    from .agent_project import AgentProjectParams
    from .agent_pronunciation_dictionary_item import AgentPronunciationDictionaryItemParams
    from .agent_template_variables_value import AgentTemplateVariablesValueParams
    from .agent_tools_item import AgentToolsItemParams
    from .api_key_with_secret import ApiKeyWithSecretParams
    from .assistant_chose_not_to_respond_payload import AssistantChoseNotToRespondPayloadParams
    from .assistant_ended_conversation_payload import AssistantEndedConversationPayloadParams
    from .assistant_finished_speaking_payload import AssistantFinishedSpeakingPayloadParams
    from .assistant_started_speaking_payload import AssistantStartedSpeakingPayloadParams
    from .audio_chunk_payload import AudioChunkPayloadParams
    from .audio_chunk_response_payload import AudioChunkResponsePayloadParams
    from .bad_request_error_body import BadRequestErrorBodyParams
    from .basic_error import BasicErrorParams
    from .basic_error_error import BasicErrorErrorParams
    from .built_in_tool_config import BuiltInToolConfigParams
    from .built_in_tool_configs import BuiltInToolConfigsParams
    from .built_in_tool_definition import BuiltInToolDefinitionParams
    from .config_options import ConfigOptionsParams
    from .config_options_configuration_endpoint import ConfigOptionsConfigurationEndpointParams
    from .config_options_data_retention_policy import ConfigOptionsDataRetentionPolicyParams
    from .config_options_data_retention_policy_audio_recordings import (
        ConfigOptionsDataRetentionPolicyAudioRecordingsParams,
    )
    from .config_options_data_retention_policy_audio_recordings_audio_recordings import (
        ConfigOptionsDataRetentionPolicyAudioRecordingsAudioRecordingsParams,
    )
    from .config_options_data_retention_policy_audio_recordings_transcripts import (
        ConfigOptionsDataRetentionPolicyAudioRecordingsTranscriptsParams,
    )
    from .config_options_data_retention_policy_zero import ConfigOptionsDataRetentionPolicyZeroParams
    from .config_options_outbound_number_pool import ConfigOptionsOutboundNumberPoolParams
    from .config_options_pronunciation_dictionary_item import ConfigOptionsPronunciationDictionaryItemParams
    from .config_options_tasks_item import ConfigOptionsTasksItemParams
    from .config_payload import ConfigPayloadParams
    from .conversation import ConversationParams
    from .conversation_agent import ConversationAgentParams
    from .conversation_analysis import ConversationAnalysisParams
    from .conversation_call_info import ConversationCallInfoParams
    from .conversation_created_payload import ConversationCreatedPayloadParams
    from .conversation_deletion_info import ConversationDeletionInfoParams
    from .conversation_eval import ConversationEvalParams
    from .conversation_eval_prompt import ConversationEvalPromptParams
    from .conversation_eval_prompt_info import ConversationEvalPromptInfoParams
    from .conversation_evaluation import ConversationEvaluationParams
    from .conversation_evaluation_result import ConversationEvaluationResultParams
    from .conversation_evaluation_result_prompt import ConversationEvaluationResultPromptParams
    from .conversation_extraction import ConversationExtractionParams
    from .conversation_extraction_schema import ConversationExtractionSchemaParams
    from .conversation_item import ConversationItemParams
    from .conversation_item_tool_calls_item import ConversationItemToolCallsItemParams
    from .conversation_item_tool_calls_item_request_body import ConversationItemToolCallsItemRequestBodyParams
    from .conversation_item_tool_calls_item_tool import ConversationItemToolCallsItemToolParams
    from .conversation_project import ConversationProjectParams
    from .conversation_pronunciation_dictionary_item import ConversationPronunciationDictionaryItemParams
    from .conversations_list_response_conversation import ConversationsListResponseConversationParams
    from .conversations_list_response_conversations import ConversationsListResponseConversationsParams
    from .conversations_list_response_conversations_pagination import (
        ConversationsListResponseConversationsPaginationParams,
    )
    from .create_agent_request import CreateAgentRequestParams
    from .create_agent_request_configuration_endpoint import CreateAgentRequestConfigurationEndpointParams
    from .create_agent_request_pronunciation_dictionary_item import CreateAgentRequestPronunciationDictionaryItemParams
    from .create_agent_request_template_variables_value import CreateAgentRequestTemplateVariablesValueParams
    from .create_agent_request_tools_item import CreateAgentRequestToolsItemParams
    from .data_retention_policy import DataRetentionPolicyParams
    from .data_retention_policy_audio_recordings import DataRetentionPolicyAudioRecordingsParams
    from .data_retention_policy_audio_recordings_audio_recordings import (
        DataRetentionPolicyAudioRecordingsAudioRecordingsParams,
    )
    from .data_retention_policy_audio_recordings_transcripts import DataRetentionPolicyAudioRecordingsTranscriptsParams
    from .data_retention_policy_zero import DataRetentionPolicyZeroParams
    from .dtmf_payload import DtmfPayloadParams
    from .error import ErrorParams
    from .error_payload import ErrorPayloadParams
    from .error_payload_error import ErrorPayloadErrorParams
    from .extraction_field import ExtractionFieldParams
    from .extraction_schema import ExtractionSchemaParams
    from .generate_reply_payload import GenerateReplyPayloadParams
    from .inline_web_socket_tool import InlineWebSocketToolParams
    from .input_cancelled_payload import InputCancelledPayloadParams
    from .input_text_payload import InputTextPayloadParams
    from .mute_payload import MutePayloadParams
    from .open_ai_function import OpenAiFunctionParams
    from .open_ai_tool import OpenAiToolParams
    from .outbound_call_config import OutboundCallConfigParams
    from .outbound_call_config_configuration_endpoint import OutboundCallConfigConfigurationEndpointParams
    from .outbound_call_config_pronunciation_dictionary_item import OutboundCallConfigPronunciationDictionaryItemParams
    from .outbound_call_config_tools_item import OutboundCallConfigToolsItemParams
    from .outbound_call_initiated_response import OutboundCallInitiatedResponseParams
    from .outbound_dry_run_response import OutboundDryRunResponseParams
    from .outbound_number_pool import OutboundNumberPoolParams
    from .project import ProjectParams
    from .project_default_agent import ProjectDefaultAgentParams
    from .ready_to_start_conversation_payload import ReadyToStartConversationPayloadParams
    from .replay_conversation_item_response import ReplayConversationItemResponseParams
    from .replay_conversation_item_response_responses_item import ReplayConversationItemResponseResponsesItemParams
    from .replay_tool_call import ReplayToolCallParams
    from .replay_tool_call_tool import ReplayToolCallToolParams
    from .reset_payload import ResetPayloadParams
    from .say_payload import SayPayloadParams
    from .set_external_id_payload import SetExternalIdPayloadParams
    from .sip_call_error import SipCallErrorParams
    from .sip_call_error_error import SipCallErrorErrorParams
    from .sip_outbound_call_initiated_response import SipOutboundCallInitiatedResponseParams
    from .sip_outbound_dry_run_response import SipOutboundDryRunResponseParams
    from .task import TaskParams
    from .tool import ToolParams
    from .tool_call_interrupted_payload import ToolCallInterruptedPayloadParams
    from .tool_call_output_payload import ToolCallOutputPayloadParams
    from .tool_call_output_processed_payload import ToolCallOutputProcessedPayloadParams
    from .tool_call_output_processed_payload_tool import ToolCallOutputProcessedPayloadToolParams
    from .tool_call_payload import ToolCallPayloadParams
    from .tool_definition import ToolDefinitionParams
    from .tool_parameter import ToolParameterParams
    from .tool_project import ToolProjectParams
    from .unmute_payload import UnmutePayloadParams
    from .update_system_prompt_payload import UpdateSystemPromptPayloadParams
    from .update_tools_subset_payload import UpdateToolsSubsetPayloadParams
    from .user_finished_speaking_payload import UserFinishedSpeakingPayloadParams
    from .user_started_speaking_payload import UserStartedSpeakingPayloadParams
    from .validation_error import ValidationErrorParams
    from .validation_error_error import ValidationErrorErrorParams
    from .voice import VoiceParams
    from .warning_payload import WarningPayloadParams
    from .warning_payload_warning import WarningPayloadWarningParams
_dynamic_imports: typing.Dict[str, str] = {
    "AddSystemMessagePayloadParams": ".add_system_message_payload",
    "AgentConfigurationEndpointParams": ".agent_configuration_endpoint",
    "AgentIntegrationParams": ".agent_integration",
    "AgentParams": ".agent",
    "AgentProjectParams": ".agent_project",
    "AgentPronunciationDictionaryItemParams": ".agent_pronunciation_dictionary_item",
    "AgentTemplateVariablesValueParams": ".agent_template_variables_value",
    "AgentToolsItemParams": ".agent_tools_item",
    "ApiKeyWithSecretParams": ".api_key_with_secret",
    "AssistantChoseNotToRespondPayloadParams": ".assistant_chose_not_to_respond_payload",
    "AssistantEndedConversationPayloadParams": ".assistant_ended_conversation_payload",
    "AssistantFinishedSpeakingPayloadParams": ".assistant_finished_speaking_payload",
    "AssistantStartedSpeakingPayloadParams": ".assistant_started_speaking_payload",
    "AudioChunkPayloadParams": ".audio_chunk_payload",
    "AudioChunkResponsePayloadParams": ".audio_chunk_response_payload",
    "BadRequestErrorBodyParams": ".bad_request_error_body",
    "BasicErrorErrorParams": ".basic_error_error",
    "BasicErrorParams": ".basic_error",
    "BuiltInToolConfigParams": ".built_in_tool_config",
    "BuiltInToolConfigsParams": ".built_in_tool_configs",
    "BuiltInToolDefinitionParams": ".built_in_tool_definition",
    "ConfigOptionsConfigurationEndpointParams": ".config_options_configuration_endpoint",
    "ConfigOptionsDataRetentionPolicyAudioRecordingsAudioRecordingsParams": ".config_options_data_retention_policy_audio_recordings_audio_recordings",
    "ConfigOptionsDataRetentionPolicyAudioRecordingsParams": ".config_options_data_retention_policy_audio_recordings",
    "ConfigOptionsDataRetentionPolicyAudioRecordingsTranscriptsParams": ".config_options_data_retention_policy_audio_recordings_transcripts",
    "ConfigOptionsDataRetentionPolicyParams": ".config_options_data_retention_policy",
    "ConfigOptionsDataRetentionPolicyZeroParams": ".config_options_data_retention_policy_zero",
    "ConfigOptionsOutboundNumberPoolParams": ".config_options_outbound_number_pool",
    "ConfigOptionsParams": ".config_options",
    "ConfigOptionsPronunciationDictionaryItemParams": ".config_options_pronunciation_dictionary_item",
    "ConfigOptionsTasksItemParams": ".config_options_tasks_item",
    "ConfigPayloadParams": ".config_payload",
    "ConversationAgentParams": ".conversation_agent",
    "ConversationAnalysisParams": ".conversation_analysis",
    "ConversationCallInfoParams": ".conversation_call_info",
    "ConversationCreatedPayloadParams": ".conversation_created_payload",
    "ConversationDeletionInfoParams": ".conversation_deletion_info",
    "ConversationEvalParams": ".conversation_eval",
    "ConversationEvalPromptInfoParams": ".conversation_eval_prompt_info",
    "ConversationEvalPromptParams": ".conversation_eval_prompt",
    "ConversationEvaluationParams": ".conversation_evaluation",
    "ConversationEvaluationResultParams": ".conversation_evaluation_result",
    "ConversationEvaluationResultPromptParams": ".conversation_evaluation_result_prompt",
    "ConversationExtractionParams": ".conversation_extraction",
    "ConversationExtractionSchemaParams": ".conversation_extraction_schema",
    "ConversationItemParams": ".conversation_item",
    "ConversationItemToolCallsItemParams": ".conversation_item_tool_calls_item",
    "ConversationItemToolCallsItemRequestBodyParams": ".conversation_item_tool_calls_item_request_body",
    "ConversationItemToolCallsItemToolParams": ".conversation_item_tool_calls_item_tool",
    "ConversationParams": ".conversation",
    "ConversationProjectParams": ".conversation_project",
    "ConversationPronunciationDictionaryItemParams": ".conversation_pronunciation_dictionary_item",
    "ConversationsListResponseConversationParams": ".conversations_list_response_conversation",
    "ConversationsListResponseConversationsPaginationParams": ".conversations_list_response_conversations_pagination",
    "ConversationsListResponseConversationsParams": ".conversations_list_response_conversations",
    "CreateAgentRequestConfigurationEndpointParams": ".create_agent_request_configuration_endpoint",
    "CreateAgentRequestParams": ".create_agent_request",
    "CreateAgentRequestPronunciationDictionaryItemParams": ".create_agent_request_pronunciation_dictionary_item",
    "CreateAgentRequestTemplateVariablesValueParams": ".create_agent_request_template_variables_value",
    "CreateAgentRequestToolsItemParams": ".create_agent_request_tools_item",
    "DataRetentionPolicyAudioRecordingsAudioRecordingsParams": ".data_retention_policy_audio_recordings_audio_recordings",
    "DataRetentionPolicyAudioRecordingsParams": ".data_retention_policy_audio_recordings",
    "DataRetentionPolicyAudioRecordingsTranscriptsParams": ".data_retention_policy_audio_recordings_transcripts",
    "DataRetentionPolicyParams": ".data_retention_policy",
    "DataRetentionPolicyZeroParams": ".data_retention_policy_zero",
    "DtmfPayloadParams": ".dtmf_payload",
    "ErrorParams": ".error",
    "ErrorPayloadErrorParams": ".error_payload_error",
    "ErrorPayloadParams": ".error_payload",
    "ExtractionFieldParams": ".extraction_field",
    "ExtractionSchemaParams": ".extraction_schema",
    "GenerateReplyPayloadParams": ".generate_reply_payload",
    "InlineWebSocketToolParams": ".inline_web_socket_tool",
    "InputCancelledPayloadParams": ".input_cancelled_payload",
    "InputTextPayloadParams": ".input_text_payload",
    "MutePayloadParams": ".mute_payload",
    "OpenAiFunctionParams": ".open_ai_function",
    "OpenAiToolParams": ".open_ai_tool",
    "OutboundCallConfigConfigurationEndpointParams": ".outbound_call_config_configuration_endpoint",
    "OutboundCallConfigParams": ".outbound_call_config",
    "OutboundCallConfigPronunciationDictionaryItemParams": ".outbound_call_config_pronunciation_dictionary_item",
    "OutboundCallConfigToolsItemParams": ".outbound_call_config_tools_item",
    "OutboundCallInitiatedResponseParams": ".outbound_call_initiated_response",
    "OutboundDryRunResponseParams": ".outbound_dry_run_response",
    "OutboundNumberPoolParams": ".outbound_number_pool",
    "ProjectDefaultAgentParams": ".project_default_agent",
    "ProjectParams": ".project",
    "ReadyToStartConversationPayloadParams": ".ready_to_start_conversation_payload",
    "ReplayConversationItemResponseParams": ".replay_conversation_item_response",
    "ReplayConversationItemResponseResponsesItemParams": ".replay_conversation_item_response_responses_item",
    "ReplayToolCallParams": ".replay_tool_call",
    "ReplayToolCallToolParams": ".replay_tool_call_tool",
    "ResetPayloadParams": ".reset_payload",
    "SayPayloadParams": ".say_payload",
    "SetExternalIdPayloadParams": ".set_external_id_payload",
    "SipCallErrorErrorParams": ".sip_call_error_error",
    "SipCallErrorParams": ".sip_call_error",
    "SipOutboundCallInitiatedResponseParams": ".sip_outbound_call_initiated_response",
    "SipOutboundDryRunResponseParams": ".sip_outbound_dry_run_response",
    "TaskParams": ".task",
    "ToolCallInterruptedPayloadParams": ".tool_call_interrupted_payload",
    "ToolCallOutputPayloadParams": ".tool_call_output_payload",
    "ToolCallOutputProcessedPayloadParams": ".tool_call_output_processed_payload",
    "ToolCallOutputProcessedPayloadToolParams": ".tool_call_output_processed_payload_tool",
    "ToolCallPayloadParams": ".tool_call_payload",
    "ToolDefinitionParams": ".tool_definition",
    "ToolParameterParams": ".tool_parameter",
    "ToolParams": ".tool",
    "ToolProjectParams": ".tool_project",
    "UnmutePayloadParams": ".unmute_payload",
    "UpdateSystemPromptPayloadParams": ".update_system_prompt_payload",
    "UpdateToolsSubsetPayloadParams": ".update_tools_subset_payload",
    "UserFinishedSpeakingPayloadParams": ".user_finished_speaking_payload",
    "UserStartedSpeakingPayloadParams": ".user_started_speaking_payload",
    "ValidationErrorErrorParams": ".validation_error_error",
    "ValidationErrorParams": ".validation_error",
    "VoiceParams": ".voice",
    "WarningPayloadParams": ".warning_payload",
    "WarningPayloadWarningParams": ".warning_payload_warning",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AddSystemMessagePayloadParams",
    "AgentConfigurationEndpointParams",
    "AgentIntegrationParams",
    "AgentParams",
    "AgentProjectParams",
    "AgentPronunciationDictionaryItemParams",
    "AgentTemplateVariablesValueParams",
    "AgentToolsItemParams",
    "ApiKeyWithSecretParams",
    "AssistantChoseNotToRespondPayloadParams",
    "AssistantEndedConversationPayloadParams",
    "AssistantFinishedSpeakingPayloadParams",
    "AssistantStartedSpeakingPayloadParams",
    "AudioChunkPayloadParams",
    "AudioChunkResponsePayloadParams",
    "BadRequestErrorBodyParams",
    "BasicErrorErrorParams",
    "BasicErrorParams",
    "BuiltInToolConfigParams",
    "BuiltInToolConfigsParams",
    "BuiltInToolDefinitionParams",
    "ConfigOptionsConfigurationEndpointParams",
    "ConfigOptionsDataRetentionPolicyAudioRecordingsAudioRecordingsParams",
    "ConfigOptionsDataRetentionPolicyAudioRecordingsParams",
    "ConfigOptionsDataRetentionPolicyAudioRecordingsTranscriptsParams",
    "ConfigOptionsDataRetentionPolicyParams",
    "ConfigOptionsDataRetentionPolicyZeroParams",
    "ConfigOptionsOutboundNumberPoolParams",
    "ConfigOptionsParams",
    "ConfigOptionsPronunciationDictionaryItemParams",
    "ConfigOptionsTasksItemParams",
    "ConfigPayloadParams",
    "ConversationAgentParams",
    "ConversationAnalysisParams",
    "ConversationCallInfoParams",
    "ConversationCreatedPayloadParams",
    "ConversationDeletionInfoParams",
    "ConversationEvalParams",
    "ConversationEvalPromptInfoParams",
    "ConversationEvalPromptParams",
    "ConversationEvaluationParams",
    "ConversationEvaluationResultParams",
    "ConversationEvaluationResultPromptParams",
    "ConversationExtractionParams",
    "ConversationExtractionSchemaParams",
    "ConversationItemParams",
    "ConversationItemToolCallsItemParams",
    "ConversationItemToolCallsItemRequestBodyParams",
    "ConversationItemToolCallsItemToolParams",
    "ConversationParams",
    "ConversationProjectParams",
    "ConversationPronunciationDictionaryItemParams",
    "ConversationsListResponseConversationParams",
    "ConversationsListResponseConversationsPaginationParams",
    "ConversationsListResponseConversationsParams",
    "CreateAgentRequestConfigurationEndpointParams",
    "CreateAgentRequestParams",
    "CreateAgentRequestPronunciationDictionaryItemParams",
    "CreateAgentRequestTemplateVariablesValueParams",
    "CreateAgentRequestToolsItemParams",
    "DataRetentionPolicyAudioRecordingsAudioRecordingsParams",
    "DataRetentionPolicyAudioRecordingsParams",
    "DataRetentionPolicyAudioRecordingsTranscriptsParams",
    "DataRetentionPolicyParams",
    "DataRetentionPolicyZeroParams",
    "DtmfPayloadParams",
    "ErrorParams",
    "ErrorPayloadErrorParams",
    "ErrorPayloadParams",
    "ExtractionFieldParams",
    "ExtractionSchemaParams",
    "GenerateReplyPayloadParams",
    "InlineWebSocketToolParams",
    "InputCancelledPayloadParams",
    "InputTextPayloadParams",
    "MutePayloadParams",
    "OpenAiFunctionParams",
    "OpenAiToolParams",
    "OutboundCallConfigConfigurationEndpointParams",
    "OutboundCallConfigParams",
    "OutboundCallConfigPronunciationDictionaryItemParams",
    "OutboundCallConfigToolsItemParams",
    "OutboundCallInitiatedResponseParams",
    "OutboundDryRunResponseParams",
    "OutboundNumberPoolParams",
    "ProjectDefaultAgentParams",
    "ProjectParams",
    "ReadyToStartConversationPayloadParams",
    "ReplayConversationItemResponseParams",
    "ReplayConversationItemResponseResponsesItemParams",
    "ReplayToolCallParams",
    "ReplayToolCallToolParams",
    "ResetPayloadParams",
    "SayPayloadParams",
    "SetExternalIdPayloadParams",
    "SipCallErrorErrorParams",
    "SipCallErrorParams",
    "SipOutboundCallInitiatedResponseParams",
    "SipOutboundDryRunResponseParams",
    "TaskParams",
    "ToolCallInterruptedPayloadParams",
    "ToolCallOutputPayloadParams",
    "ToolCallOutputProcessedPayloadParams",
    "ToolCallOutputProcessedPayloadToolParams",
    "ToolCallPayloadParams",
    "ToolDefinitionParams",
    "ToolParameterParams",
    "ToolParams",
    "ToolProjectParams",
    "UnmutePayloadParams",
    "UpdateSystemPromptPayloadParams",
    "UpdateToolsSubsetPayloadParams",
    "UserFinishedSpeakingPayloadParams",
    "UserStartedSpeakingPayloadParams",
    "ValidationErrorErrorParams",
    "ValidationErrorParams",
    "VoiceParams",
    "WarningPayloadParams",
    "WarningPayloadWarningParams",
]
