# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class AgentIntegrationParams(typing_extensions.TypedDict):
    """
    A third-party integration enabled for an agent.
    """

    account_id: str
    """
    The connected account ID.
    """

    account_name: typing.Optional[str]
    """
    The connected account name.
    """

    action_names: typing.Sequence[str]
    """
    The integration actions available to the agent.
    """

    app_slug: str
    """
    The slug identifying the integration app.
    """
