# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ApiKeyWithSecretParams(typing_extensions.TypedDict):
    id: str
    """
    The API key ID.
    """

    name: str
    """
    The name of the API key.
    """

    api_key: str
    """
    The API key secret. Only returned once, when the key is created or rotated.
    """
