# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class AssistantStartedSpeakingPayloadParams(typing_extensions.TypedDict):
    type: typing.Literal["assistant_started_speaking"]
