# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.built_in_tool_config_speech_before_tool_call import BuiltInToolConfigSpeechBeforeToolCall


class BuiltInToolConfigParams(typing_extensions.TypedDict):
    """
    Configuration for a simple built-in tool (`keypad_input`, `natural_conversation_ending`, or `choose_not_to_respond`).
    """

    speech_before_tool_call: BuiltInToolConfigSpeechBeforeToolCall
    """
    Controls whether the assistant speaks before the tool is called. `required`: the assistant must speak first. `optional`: the model decides. `suppressed`: the assistant is strongly instructed to stay silent before the call (best effort).
    """
