# This file was auto-generated by Fern from our API Definition.

import typing

from ..types.built_in_tool_config import BuiltInToolConfig

BuiltInToolConfigsParams = typing.Dict[str, BuiltInToolConfig]
