# This file was auto-generated by Fern from our API Definition.

import typing

from ..types.built_in_tool_configs_value import BuiltInToolConfigsValue

BuiltInToolConfigsParams = typing.Dict[str, BuiltInToolConfigsValue]
