# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class ChooseNotToRespondToolConfigParams(typing_extensions.TypedDict):
    """
    Configuration for the `choose_not_to_respond` built-in tool.
    """

    respond_after_sec: typing_extensions.NotRequired[typing.Optional[float]]
    """
    Number of seconds to wait after the tool fires before the assistant speaks a follow-up if the user stays silent. When null, the assistant stays silent (default).
    """
