# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.config_options_background_noise import ConfigOptionsBackgroundNoise
from ..types.config_options_input_format import ConfigOptionsInputFormat
from ..types.config_options_multilingual_mode import ConfigOptionsMultilingualMode
from ..types.config_options_output_format import ConfigOptionsOutputFormat
from .config_options_tools_item import ConfigOptionsToolsItemParams


class ConfigOptionsParams(typing_extensions.TypedDict):
    """
    Configuration fields for the initial `config` message.
    """

    agent: typing_extensions.NotRequired[str]
    """
    Agent name to use for conversation
    """

    project: typing_extensions.NotRequired[str]
    """
    Project name
    """

    model: typing_extensions.NotRequired[typing.Literal["merritt"]]
    """
    STS model to use
    """

    system_prompt: typing_extensions.NotRequired[str]
    """
    System prompt for AI assistant
    """

    audio_speed: typing_extensions.NotRequired[float]
    """
    Audio playback speed
    """

    background_noise_level: typing_extensions.NotRequired[float]
    """
    Background noise level for the conversation
    """

    background_noise: typing_extensions.NotRequired[typing.Optional[ConfigOptionsBackgroundNoise]]
    """
    Background noise type for the conversation
    """

    generate_welcome_message: typing_extensions.NotRequired[bool]
    """
    When `true`, the welcome message will be automatically generated and the `welcome_message` field will be ignored.
    """

    welcome_message: typing_extensions.NotRequired[typing.Optional[str]]
    """
    Message to play when conversation starts. Ignored when `generate_welcome_message` is `true`.
    """

    voice_id: typing_extensions.NotRequired[str]
    """
    Voice ID to use for speech synthesis
    """

    input_format: typing_extensions.NotRequired[ConfigOptionsInputFormat]
    """
    Audio input format
    """

    output_format: typing_extensions.NotRequired[ConfigOptionsOutputFormat]
    """
    Audio output format
    """

    vad_prebuffer_duration_ms: typing_extensions.NotRequired[int]
    """
    Voice activity detection prebuffer duration
    """

    vad_min_speech_duration_ms: typing_extensions.NotRequired[int]
    """
    Minimum speech duration for VAD
    """

    vad_min_silence_duration_ms: typing_extensions.NotRequired[int]
    """
    Minimum silence duration for VAD
    """

    vad_threshold: typing_extensions.NotRequired[float]
    """
    Voice activity detection threshold
    """

    min_words_to_interrupt: typing_extensions.NotRequired[int]
    """
    Minimum number of words required to interrupt the assistant.
    """

    generate_no_input_poke_text: typing_extensions.NotRequired[bool]
    """
    Whether to have the no-input poke text be generated by AI
    """

    no_input_poke_sec: typing_extensions.NotRequired[typing.Optional[int]]
    """
    Seconds of silence before poke message
    """

    no_input_poke_text: typing_extensions.NotRequired[str]
    """
    Poke message text. Ignored when generate_no_input_poke_text is true.
    """

    no_input_end_conversation_sec: typing_extensions.NotRequired[int]
    """
    Seconds of silence before ending conversation
    """

    default_language: typing_extensions.NotRequired[str]
    """
    ISO 639-1 language code that sets the agent's default language to recognize and speak. Welcome message and no input poke text should be in this language.
    """

    additional_languages: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    Array of additional ISO 639-1 language codes that the agent should be able to recognize and speak. Should not include `default_language`.
    """

    multilingual_mode: typing_extensions.NotRequired[ConfigOptionsMultilingualMode]
    """
    If `"auto"`, each user audio is automatically identified for the language to respond in. If `"request"`, user must request to change language (recommended).
    """

    boosted_keywords: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    Keywords to boost in speech recognition
    """

    tools: typing_extensions.NotRequired[typing.Sequence[ConfigOptionsToolsItemParams]]
    """
    Names of tools available to the assistant.
    """

    template_variables: typing_extensions.NotRequired[typing.Dict[str, str]]
    """
    Template variables for system prompt and welcome message
    """
