# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ConfigOptionsTasksItemParams(typing_extensions.TypedDict):
    name: str
    """
    Name of the task.
    """

    description: str
    """
    Description of the task.
    """
