# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class ConfigOptionsDataRetentionPolicyAudioRecordingsTranscriptsParams(typing_extensions.TypedDict):
    delete_after_hours: typing.Optional[int]
    """
    Number of hours after which transcripts are deleted. When `null`, transcripts are retained indefinitely.
    """
