# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.config_options_background_noise import ConfigOptionsBackgroundNoise
from ..types.config_options_input_format import ConfigOptionsInputFormat
from ..types.config_options_intelligence_level import ConfigOptionsIntelligenceLevel
from ..types.config_options_multilingual_mode import ConfigOptionsMultilingualMode
from ..types.config_options_output_format import ConfigOptionsOutputFormat
from .config_options_configuration_endpoint import ConfigOptionsConfigurationEndpointParams
from .config_options_data_retention_policy import ConfigOptionsDataRetentionPolicyParams
from .config_options_outbound_number_pool import ConfigOptionsOutboundNumberPoolParams
from .config_options_pronunciation_dictionary_item import ConfigOptionsPronunciationDictionaryItemParams
from .config_options_tasks_item import ConfigOptionsTasksItemParams
from .tool_definition import ToolDefinitionParams


class ConfigOptionsParams(typing_extensions.TypedDict):
    """
    Configuration fields for the initial `config` message.
    """

    agent: typing_extensions.NotRequired[str]
    """
    Agent name to use for conversation
    """

    project: typing_extensions.NotRequired[str]
    """
    Project name
    """

    model: typing_extensions.NotRequired[typing.Literal["merritt"]]
    """
    STS model to use
    """

    system_prompt: typing_extensions.NotRequired[str]
    """
    System prompt for AI assistant
    """

    audio_speed: typing_extensions.NotRequired[float]
    """
    Audio playback speed
    """

    background_noise_level: typing_extensions.NotRequired[float]
    """
    Background noise level for the conversation
    """

    background_noise: typing_extensions.NotRequired[typing.Optional[ConfigOptionsBackgroundNoise]]
    """
    Background noise type for the conversation
    """

    generate_welcome_message: typing_extensions.NotRequired[bool]
    """
    When `true`, the welcome message will be automatically generated and the `welcome_message` field will be ignored.
    """

    is_welcome_message_interruptible: typing_extensions.NotRequired[bool]
    """
    When `false`, the welcome message will not be interruptible by the user.
    """

    websocket_timeout_sec: typing_extensions.NotRequired[int]
    """
    Number of seconds of inactivity before the conversation WebSocket is closed.
    """

    welcome_message: typing_extensions.NotRequired[typing.Optional[str]]
    """
    Message to play when conversation starts. Ignored when `generate_welcome_message` is `true`.
    """

    voice_id: typing_extensions.NotRequired[str]
    """
    Voice ID to use for speech synthesis
    """

    input_format: typing_extensions.NotRequired[ConfigOptionsInputFormat]
    """
    Audio input format
    """

    output_format: typing_extensions.NotRequired[ConfigOptionsOutputFormat]
    """
    Audio output format
    """

    vad_prebuffer_duration_ms: typing_extensions.NotRequired[int]
    """
    Voice activity detection prebuffer duration
    """

    vad_min_speech_duration_ms: typing_extensions.NotRequired[int]
    """
    Minimum speech duration for VAD
    """

    vad_min_silence_duration_ms: typing_extensions.NotRequired[int]
    """
    Minimum silence duration for VAD
    """

    vad_threshold: typing_extensions.NotRequired[float]
    """
    Voice activity detection threshold
    """

    min_words_to_interrupt: typing_extensions.NotRequired[int]
    """
    Minimum number of words required to interrupt the assistant.
    """

    generate_no_input_poke_text: typing_extensions.NotRequired[bool]
    """
    Whether to have the no-input poke text be generated by AI
    """

    no_input_poke_sec: typing_extensions.NotRequired[typing.Optional[int]]
    """
    Seconds of silence before poke message
    """

    no_input_poke_text: typing_extensions.NotRequired[str]
    """
    Poke message text. Ignored when generate_no_input_poke_text is true.
    """

    no_input_end_conversation_sec: typing_extensions.NotRequired[int]
    """
    Seconds of silence before ending conversation
    """

    default_language: typing_extensions.NotRequired[str]
    """
    ISO 639-1 language code that sets the agent's default language to recognize and speak. Welcome message and no input poke text should be in this language.
    """

    additional_languages: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    Array of additional ISO 639-1 language codes that the agent should be able to recognize and speak. Should not include `default_language`. When `multilingual_mode` is `"auto"`, a maximum of 2 additional languages is allowed.
    """

    multilingual_mode: typing_extensions.NotRequired[ConfigOptionsMultilingualMode]
    """
    If `"auto"`, each user audio is automatically identified for the language to respond in. If `"request"`, user must request to change language (recommended). If `"initial"` the first turn user audio determines the language for the rest of the conversation.
    """

    push_to_talk: typing_extensions.NotRequired[bool]
    """
    Push to talk mode. User must send mute/unmute messages to turn on/off listening to audio. Defaults to false.
    """

    stream_ahead_of_real_time: typing_extensions.NotRequired[bool]
    """
    When `true`, assistant audio is streamed to the client as fast as it is generated, rather than paced to real time. Defaults to false.
    """

    intelligence_level: typing_extensions.NotRequired[ConfigOptionsIntelligenceLevel]
    """
    The intelligence level of the agent. `high` uses a more capable model for more complex reasoning, while `standard` is optimized for lower latency.
    """

    boosted_keywords: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    Keywords to boost in speech recognition
    """

    pronunciation_dictionary: typing_extensions.NotRequired[
        typing.Sequence[ConfigOptionsPronunciationDictionaryItemParams]
    ]
    """
    Array of `{ word, pronunciation }` entries. Words must be unique.
    """

    tools: typing_extensions.NotRequired[typing.Sequence[ToolDefinitionParams]]
    """
    Tools available to the assistant. Use a string to reference a pre-defined tool by name, provide a built-in tool object to override its default configuration, or define an inline WebSocket tool for this conversation.
    """

    template_variables: typing_extensions.NotRequired[typing.Dict[str, str]]
    """
    Template variables for system prompt and welcome message
    """

    enable_redaction: typing_extensions.NotRequired[bool]
    """
    When `true`, PII and PHI are redacted from text transcripts (e.g. replaced with tags like `[PHONE NUMBER]`) and bleeped from audio recordings after the conversation ends.
    """

    mcp_servers: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    Names of pre-configured MCP servers to make available to the assistant. Names must be unique.
    """

    observability_integrations: typing_extensions.NotRequired[typing.Sequence[typing.Literal["braintrust"]]]
    """
    Names of observability integrations to enable for the conversation. Each must be one of the supported providers.
    """

    tasks: typing_extensions.NotRequired[typing.Sequence[ConfigOptionsTasksItemParams]]
    """
    Tasks the assistant should accomplish during the conversation.
    """

    outbound_number_pool: typing_extensions.NotRequired[typing.Optional[ConfigOptionsOutboundNumberPoolParams]]
    """
    Pool of phone numbers to use as the caller ID for outbound calls.
    """

    enable_assistant_backchannel: typing_extensions.NotRequired[bool]
    """
    When `true`, the assistant will produce backchannel responses (e.g. "mm-hmm", "yeah") while the user is speaking.
    """

    assistant_backchannel_aggressiveness: typing_extensions.NotRequired[float]
    """
    How aggressively the assistant produces backchannel responses. Only applies when `enable_assistant_backchannel` is `true`.
    """

    configuration_endpoint: typing_extensions.NotRequired[typing.Optional[ConfigOptionsConfigurationEndpointParams]]
    """
    When not `null`, the agent will call this endpoint to get configuration options for the conversation.
    """

    additional_params: typing_extensions.NotRequired[typing.Dict[str, typing.Any]]
    """
    Additional runtime parameters.
    """

    data_retention_policy: typing_extensions.NotRequired[ConfigOptionsDataRetentionPolicyParams]
    """
    Policy controlling how long transcripts and audio recordings are retained before being deleted.
    When `zero_data_retention` is `true`, nothing is retained and `transcripts`/`audio_recordings` are omitted.
    """
