# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ConversationCallInfoParams(typing_extensions.TypedDict):
    """
    Phone call metadata. `null` for non-phone call conversations.
    """

    from_phone_number: str
    """
    Caller phone number in E.164 format. `"anonymous"` for inbound calls whose caller withheld their number.
    """

    to_phone_number: str
    """
    Callee phone number in E.164 format.
    """

    twilio_call_sid: typing_extensions.NotRequired[str]
    """
    Twilio Call SID. Only present for user SIP trunking calls.
    """
