# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class DataRetentionPolicyAudioRecordingsTranscriptsParams(typing_extensions.TypedDict):
    delete_after_hours: typing.Optional[int]
    """
    Number of hours after which transcripts are deleted. Null means transcripts are retained indefinitely.
    """
