# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class DataRetentionPolicyZeroParams(typing_extensions.TypedDict):
    """
    Zero data retention mode. No transcripts or audio recordings are retained.
    """

    zero_data_retention: typing.Literal[True]
    """
    When `true`, no transcripts or audio recordings are retained.
    """
