# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class DataRetentionPolicyAudioRecordingsAudioRecordingsParams(typing_extensions.TypedDict):
    delete_after_hours: typing.Optional[int]
    """
    Number of hours after which audio recordings are deleted. Null means audio recordings are retained indefinitely.
    """
