# This file was auto-generated by Fern from our API Definition.

import typing

from .data_retention_policy_audio_recordings import DataRetentionPolicyAudioRecordingsParams
from .data_retention_policy_zero import DataRetentionPolicyZeroParams

DataRetentionPolicyParams = typing.Union[DataRetentionPolicyZeroParams, DataRetentionPolicyAudioRecordingsParams]
