# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .data_retention_policy_audio_recordings_audio_recordings import (
    DataRetentionPolicyAudioRecordingsAudioRecordingsParams,
)
from .data_retention_policy_audio_recordings_transcripts import DataRetentionPolicyAudioRecordingsTranscriptsParams


class DataRetentionPolicyAudioRecordingsParams(typing_extensions.TypedDict):
    """
    Standard data retention with configurable deletion windows.
    """

    zero_data_retention: typing.Literal[False]
    """
    Must be `false` for standard data retention.
    """

    transcripts: DataRetentionPolicyAudioRecordingsTranscriptsParams
    audio_recordings: DataRetentionPolicyAudioRecordingsAudioRecordingsParams
