# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.external_storage_policy_addressing_style import ExternalStoragePolicyAddressingStyle


class ExternalStoragePolicyParams(typing_extensions.TypedDict):
    """
    An S3-compatible destination that conversation artifacts are delivered to.
    """

    id: str
    """
    The ID of the external storage policy.
    """

    name: str
    """
    The name of the external storage policy. Agents reference the policy by this name.
    """

    endpoint_url: str
    """
    The S3-compatible endpoint URL that artifacts are uploaded to.
    """

    bucket: str
    """
    The bucket that artifacts are uploaded to.
    """

    region: typing.Optional[str]
    """
    The region of the bucket. `null` when the endpoint doesn't require a region.
    """

    key_prefix: typing.Optional[str]
    """
    Prefix prepended to every object key. `null` when objects are written at the bucket root.
    """

    addressing_style: ExternalStoragePolicyAddressingStyle
    """
    How bucket names are addressed in requests to the endpoint.
    """

    agent_count: int
    """
    Number of agents currently referencing this external storage policy.
    """
