# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .generated_response import GeneratedResponseParams


class GenerateResponsesResponseParams(typing_extensions.TypedDict):
    responses: typing.Sequence[GeneratedResponseParams]
    """
    The generated responses - always `num_responses` of them.
    """
