# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class GeneratedToolCallParams(typing_extensions.TypedDict):
    tool_call_id: str
    """
    Identifier for this tool call. Send it back as the `tool_call_id` of the matching `tool_call_output` input item.
    """

    tool_name: str
    """
    Name of the tool to call. Always one of the `tool_definitions` from the request.
    """

    request_body: typing_extensions.NotRequired[typing.Dict[str, typing.Any]]
    """
    Arguments the assistant produced for the request body.
    """

    query_params: typing_extensions.NotRequired[typing.Dict[str, str]]
    """
    Arguments the assistant produced as query parameters.
    """
