# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class GenerateReplyPayloadParams(typing_extensions.TypedDict):
    type: typing.Literal["generate_reply"]
    system_message: typing_extensions.NotRequired[typing.Optional[str]]
    """
    Optional system message to guide the assistant's reply
    """
