# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .generated_tool_call import GeneratedToolCallParams


class GeneratedResponseParams(typing_extensions.TypedDict):
    text: str
    """
    The text the assistant would say. Empty when the response only makes tool calls.
    """

    tool_calls: typing.Sequence[GeneratedToolCallParams]
    """
    Tool calls the assistant would make - note that the tools are not actually called.
    """
