# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .conversation import ConversationParams


class GetConversationByExternalIdResponseParams(typing_extensions.TypedDict):
    conversation: ConversationParams
