# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class InterruptedResponsePayloadParams(typing_extensions.TypedDict):
    type: typing.Literal["interrupted_response"]
    text: str
    """
    The part of the assistant's turn that was spoken before the user interrupted.
    """
