# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .conversation import ConversationParams
from .list_conversations_response_pagination import ListConversationsResponsePaginationParams


class ListConversationsResponseParams(typing_extensions.TypedDict):
    conversations: typing.Sequence[ConversationParams]
    pagination: ListConversationsResponsePaginationParams
