# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .open_ai_function import OpenAiFunctionParams


class OpenAiToolParams(typing_extensions.TypedDict):
    """
    OpenAI-compatible function tool schema.
    """

    type: typing.Literal["function"]
    function: OpenAiFunctionParams
