# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.language_code import LanguageCode
from ..types.outbound_call_config_background_noise import OutboundCallConfigBackgroundNoise
from ..types.outbound_call_config_multilingual_mode import OutboundCallConfigMultilingualMode
from .data_retention_policy import DataRetentionPolicyParams
from .outbound_call_config_configuration_endpoint import OutboundCallConfigConfigurationEndpointParams
from .outbound_call_config_pronunciation_dictionary_item import OutboundCallConfigPronunciationDictionaryItemParams
from .outbound_call_config_tools_item import OutboundCallConfigToolsItemParams
from .outbound_number_pool import OutboundNumberPoolParams
from .task import TaskParams


class OutboundCallConfigParams(typing_extensions.TypedDict):
    """
    When an `agent` is provided, these `config` options override the agent settings.
    """

    agent: typing_extensions.NotRequired[str]
    """
    The name of the agent to use for the call.
    """

    project: typing_extensions.NotRequired[str]
    """
    The name of the project to use for the call.
    """

    generate_welcome_message: typing_extensions.NotRequired[bool]
    """
    When `true`, the welcome message will be automatically generated and the `welcome_message` field will be ignored.
    """

    is_welcome_message_interruptible: typing_extensions.NotRequired[bool]
    """
    When `false`, the welcome message will not be interruptible by the user.
    """

    welcome_message: typing_extensions.NotRequired[typing.Optional[str]]
    """
    Message to play when the conversation starts. Can contain template variables like `{{customer_name}}`. Ignored when `generate_welcome_message` is `true`.
    """

    system_prompt: typing_extensions.NotRequired[str]
    """
    Instructions for the conversation. Can contain template variables like `{{subject}}`.
    """

    template_variables: typing_extensions.NotRequired[typing.Dict[str, str]]
    """
    Variables that can be used in the welcome message and the system prompt.
    """

    voice_id: typing_extensions.NotRequired[str]
    """
    The voice ID to use for the agent.
    """

    generate_no_input_poke_text: typing_extensions.NotRequired[bool]
    """
    Whether to have the no-input poke text be generated by AI.
    """

    no_input_poke_sec: typing_extensions.NotRequired[typing.Optional[int]]
    """
    Number of seconds of silence before sending a poke message. `null` disables the poke message.
    """

    no_input_poke_text: typing_extensions.NotRequired[str]
    """
    The message to send after the specified silence. Ignored when generate_no_input_poke_text is true.
    """

    no_input_end_conversation_sec: typing_extensions.NotRequired[int]
    """
    Seconds of silence before ending the conversation.
    """

    default_language: typing_extensions.NotRequired[LanguageCode]
    """
    ISO 639-1 language code that sets the agent's default language to recognize and speak. Welcome message and no input poke text should be in this language.
    """

    additional_languages: typing_extensions.NotRequired[typing.Sequence[LanguageCode]]
    """
    Array of additional ISO 639-1 language codes that the agent should be able to recognize and speak. Should not include `default_language`. When `multilingual_mode` is `"auto"`, a maximum of 2 additional languages is allowed.
    """

    languages: typing_extensions.NotRequired[typing.Sequence[LanguageCode]]
    """
    Array of ISO 639-1 language codes that the agent should be able to recognize. This field is deprecated. Use `default_language` and `additional_languages` instead.
    """

    multilingual_mode: typing_extensions.NotRequired[OutboundCallConfigMultilingualMode]
    """
    If `"auto"`, each user audio is automatically identified for the language to respond in. If `"request"`, user must request to change language (recommended). If `"initial"` the first turn user audio determines the language for the rest of the conversation.
    """

    push_to_talk: typing_extensions.NotRequired[bool]
    """
    Push to talk mode. User must send mute/unmute messages to turn on/off listening to audio. Defaults to false.
    """

    boosted_keywords: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    These words, or short phrases, will be more accurately recognized by the agent.
    """

    pronunciation_dictionary: typing_extensions.NotRequired[
        typing.Sequence[OutboundCallConfigPronunciationDictionaryItemParams]
    ]
    """
    Array of `{ word, pronunciation }` entries. Words must be unique.
    """

    min_words_to_interrupt: typing_extensions.NotRequired[int]
    """
    Minimum number of words required to interrupt the assistant.
    """

    tools: typing_extensions.NotRequired[typing.Sequence[OutboundCallConfigToolsItemParams]]
    """
    Array of built-in or custom tool names to use.
    """

    enable_redaction: typing_extensions.NotRequired[bool]
    """
    When `true`, PII and PHI are redacted from text transcripts (e.g. replaced with tags like `[PHONE NUMBER]`) and bleeped from audio recordings after the conversation ends.
    """

    model: typing_extensions.NotRequired[typing.Literal["merritt"]]
    """
    The speech-to-speech model to use.
    """

    audio_speed: typing_extensions.NotRequired[float]
    """
    The audio speed of the agent.
    """

    background_noise: typing_extensions.NotRequired[typing.Optional[OutboundCallConfigBackgroundNoise]]
    """
    The background noise type. Can be "office", "call-center", "coffee-shop", or null.
    """

    background_noise_level: typing_extensions.NotRequired[float]
    """
    The background noise level of the agent.
    """

    mcp_servers: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    Array of MCP server names to use.
    """

    tasks: typing_extensions.NotRequired[typing.Sequence[TaskParams]]
    """
    Array of task objects with `name` and `description` fields.
    """

    outbound_number_pool: typing_extensions.NotRequired[typing.Optional[OutboundNumberPoolParams]]
    """
    Pool of phone numbers used for outbound calls.
    """

    enable_assistant_backchannel: typing_extensions.NotRequired[bool]
    """
    When `true`, the assistant will produce backchannel responses (e.g. "mm-hmm") while the user is speaking.
    """

    assistant_backchannel_aggressiveness: typing_extensions.NotRequired[float]
    """
    How aggressively the assistant produces backchannel responses. Only relevant when `enable_assistant_backchannel` is `true`.
    """

    configuration_endpoint: typing_extensions.NotRequired[
        typing.Optional[OutboundCallConfigConfigurationEndpointParams]
    ]
    """
    When not `null`, at the beginning of the conversation the agent will make a POST request to this endpoint to get configuration options.
    """

    data_retention_policy: typing_extensions.NotRequired[DataRetentionPolicyParams]
    """
    Controls how long transcripts and audio recordings are retained before deletion.
    """
