# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class OutboundCallConfigPronunciationDictionaryItemParams(typing_extensions.TypedDict):
    word: str
    pronunciation: str
