# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .project_default_agent import ProjectDefaultAgentParams


class ProjectParams(typing_extensions.TypedDict):
    id: str
    """
    The ID of the project.
    """

    name: str
    """
    The name of the project.
    """

    default_agent: typing.Optional[ProjectDefaultAgentParams]
    """
    The project's default agent.
    """

    active_conversations: int
    """
    Number of conversations currently in progress for this project.
    """

    max_active_conversations: typing.Optional[int]
    """
    Maximum number of concurrent conversations allowed for this project. When `null`, the workspace `max_active_conversations` limit is used.
    """
