# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.replay_tool_call_endpoint_method import ReplayToolCallEndpointMethod
from .replay_tool_call_tool import ReplayToolCallToolParams


class ReplayToolCallParams(typing_extensions.TypedDict):
    tool: ReplayToolCallToolParams
    endpoint_method: typing_extensions.NotRequired[ReplayToolCallEndpointMethod]
    """
    HTTP method for webhook tool calls.
    """

    endpoint_url: typing_extensions.NotRequired[str]
    """
    URL for webhook tool calls.
    """

    endpoint_headers: typing_extensions.NotRequired[typing.Optional[typing.Dict[str, typing.Optional[str]]]]
    """
    Headers for webhook tool calls.
    """

    query_params: typing_extensions.NotRequired[typing.Optional[typing.Dict[str, typing.Optional[str]]]]
    """
    Query parameters the LLM produced for webhook tool calls.
    """

    context: typing_extensions.NotRequired[str]
    """
    Context returned from custom-context tool calls.
    """

    request_body: typing.Optional[typing.Dict[str, typing.Any]]
    """
    Request body the LLM produced for the tool call.
    """
