# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .replay_conversation_item_response_responses_item import ReplayConversationItemResponseResponsesItemParams


class ReplayConversationItemResponseParams(typing_extensions.TypedDict):
    responses: typing.Sequence[ReplayConversationItemResponseResponsesItemParams]
    """
    Alternative responses generated for the conversation item.
    """
