# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .config_options import ConfigOptionsParams


class ResetPayloadParams(typing_extensions.TypedDict):
    type: typing.Literal["reset"]
    config: ConfigOptionsParams
