# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .tool_parameters_json_schema import ToolParametersJsonSchemaParams


class ResponsesToolDefinitionParams(typing_extensions.TypedDict):
    """
    A tool the assistant may call, defined inline for this request only.
    """

    name: str
    """
    The tool name.
    """

    description: str
    """
    What the tool does. The model uses this to decide when to call it.
    """

    parameters: ToolParametersJsonSchemaParams
