# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .responses_tool_call import ResponsesToolCallParams


class ResponsesAssistantMessageParams(typing_extensions.TypedDict):
    """
    An assistant turn. Must carry `text`, `tool_calls`, or both.
    """

    role: typing.Literal["assistant"]
    text: str
    """
    What the assistant said. Empty when the turn only made tool calls.
    """

    tool_calls: typing_extensions.NotRequired[typing.Sequence[ResponsesToolCallParams]]
    """
    Tool calls the assistant made on this turn. Each one must be followed immediately by its matching `tool_call_output` item.
    """
