# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.responses_transfer_to_phone_number_action_on_transfer_no_answer import (
    ResponsesTransferToPhoneNumberActionOnTransferNoAnswer,
)


class ResponsesTransferToPhoneNumberActionParams(typing_extensions.TypedDict):
    """
    The assistant transferred the call to a phone number (a `built_in_transfer_to_phone_number` tool).
    """

    phone_number: str
    """
    The phone number the call would be transferred to, in E.164 format.
    """

    detect_voicemail: bool
    """
    Whether Phonic would detect whether the transfer reached a voicemail.
    """

    use_agent_phone_number: bool
    """
    Whether the transfer would be placed from the agent's phone number.
    """

    keep_listening: bool
    """
    Whether Phonic would keep transcribing the call after the transfer.
    """

    on_transfer_no_answer: ResponsesTransferToPhoneNumberActionOnTransferNoAnswer
    """
    What Phonic would do if the transfer target does not answer. `return_to_assistant` hands control back to the agent; `keep_retrying` re-dials the target.
    """

    dtmf: typing_extensions.NotRequired[typing.Optional[str]]
    """
    Digits to dial after the transfer connects, for navigating a phone menu. Null when there are none.
    """
