# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ResponsesTransferToAgentActionParams(typing_extensions.TypedDict):
    """
    The assistant transferred the conversation to another agent (a `built_in_transfer_to_agent` tool).
    """

    agent: str
    """
    Name of the agent the conversation would be transferred to.
    """
