# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ResponsesToolReferenceParams(typing_extensions.TypedDict):
    """
    A pointer to the tool that was called by the assistant (see ResponsesToolCall).
    """

    id: typing_extensions.NotRequired[str]
    """
    Optional tool ID, accepted for compatibility with tool calls copied from conversation items.
    """

    name: str
    """
    Name of the tool that was called.
    """
