# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ResponsesDtmfActionParams(typing_extensions.TypedDict):
    """
    The assistant pressed keypad digits (the `keypad_input` built-in tool).
    """

    digits: str
    """
    The digits the assistant pressed.
    """
