# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class ResponsesToolCallParams(typing_extensions.TypedDict):
    """
    A tool call the assistant made earlier in the conversation.
    """

    tool_call_id: str
    """
    Identifier for this tool call, unique within `input`.
    """

    tool_name: str
    """
    Name of the called tool.
    """

    request_body: typing_extensions.NotRequired[typing.Optional[typing.Dict[str, typing.Any]]]
    """
    Arguments the assistant passed in the request body.
    """

    query_params: typing_extensions.NotRequired[typing.Optional[typing.Dict[str, typing.Optional[str]]]]
    """
    Arguments the assistant passed as query parameters. An argument cannot appear in both `request_body` and `query_params`.
    """
