# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class ResponsesUserMessageParams(typing_extensions.TypedDict):
    """
    Something the user said.
    """

    role: typing.Literal["user"]
    text: str
    """
    What the user said.
    """
