# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class ResponsesChoseNotToRespondActionParams(typing_extensions.TypedDict):
    """
    The assistant stayed silent instead of responding (the `choose_not_to_respond` built-in tool).
    """

    respond_after_sec: typing_extensions.NotRequired[typing.Optional[float]]
    """
    Number of seconds the assistant would wait before speaking a follow-up if the user stays silent, echoed from the tool's configuration. When null, the assistant stays silent.
    """
