# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .tool_parameters_json_schema import ToolParametersJsonSchemaParams


class ResponsesToolDefinitionParams(typing_extensions.TypedDict):
    """
    A tool the assistant may call, defined inline for this request only.
    """

    name: str
    """
    The tool name.
    """

    description: str
    """
    What the tool does. The model uses this to decide when to call it.
    """

    parameters: ToolParametersJsonSchemaParams
    require_speech_before_tool_call: typing_extensions.NotRequired[bool]
    """
    When true, forces the agent to speak before executing the tool. Note this defaults to true here, unlike on the tools API, so a simulated turn matches the default a custom tool runs with in a live call.
    """

    forbid_tool_call_after_speech: typing_extensions.NotRequired[bool]
    """
    When true, forbids the agent from calling the tool right after it has spoken. The call is dropped and the speech is kept.
    """
