# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ResponsesEndedConversationActionParams(typing_extensions.TypedDict):
    """
    The assistant ended the conversation (the `natural_conversation_ending` built-in tool).
    """

    pass
