# This file was auto-generated by Fern from our API Definition.

import typing

from ..types.responses_tool_name import ResponsesToolName
from .responses_built_in_tool import ResponsesBuiltInToolParams

ResponsesToolParams = typing.Union[ResponsesToolName, ResponsesBuiltInToolParams]
