# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class SayPayloadParams(typing_extensions.TypedDict):
    type: typing.Literal["say"]
    text: str
    """
    The text for the assistant to say
    """

    interruptible: typing_extensions.NotRequired[bool]
    """
    Optional configuration to make the turn interruptible or not interruptible
    """
