# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class SipOutboundCallInitiatedResponseParams(typing_extensions.TypedDict):
    conversation_id: str
    """
    The ID of the created conversation.
    """

    twilio_call_sid: str
    """
    The Twilio Call SID.
    """

    dry_run: typing.Literal[False]
    """
    Always false when a call was placed.
    """
