# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .sip_call_error_error import SipCallErrorErrorParams


class SipCallErrorParams(typing_extensions.TypedDict):
    error: SipCallErrorErrorParams
