# This file was auto-generated by Fern from our API Definition.

import typing

from ..types.tool_name import ToolName
from .built_in_tool_definition import BuiltInToolDefinitionParams
from .inline_web_socket_tool import InlineWebSocketToolParams

ToolDefinitionParams = typing.Union[ToolName, BuiltInToolDefinitionParams, InlineWebSocketToolParams]
