# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class TtsResponseParams(typing_extensions.TypedDict):
    audio: str
    """
    The generated speech, base64-encoded in the requested `output_format`.
    """
