# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .tool_definition import ToolDefinitionParams


class UpdateToolsSubsetPayloadParams(typing_extensions.TypedDict):
    type: typing.Literal["update_tools_subset"]
    tools: typing.Sequence[ToolDefinitionParams]
    """
    Tools available to the assistant. Use a string to reference a pre-defined tool by name, or define an inline WebSocket tool for this conversation. Tool names must be unique.
    """
