# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .warning_payload_warning import WarningPayloadWarningParams


class WarningPayloadParams(typing_extensions.TypedDict):
    type: typing.Literal["warning"]
    warning: WarningPayloadWarningParams
