# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawExternalStoragePoliciesClient, RawExternalStoragePoliciesClient
from .types.create_external_storage_policy_request_addressing_style import (
    CreateExternalStoragePolicyRequestAddressingStyle,
)
from .types.external_storage_policies_create_response import ExternalStoragePoliciesCreateResponse
from .types.external_storage_policies_delete_response import ExternalStoragePoliciesDeleteResponse
from .types.external_storage_policies_get_response import ExternalStoragePoliciesGetResponse
from .types.external_storage_policies_list_response import ExternalStoragePoliciesListResponse
from .types.external_storage_policies_update_response import ExternalStoragePoliciesUpdateResponse
from .types.update_external_storage_policy_request_addressing_style import (
    UpdateExternalStoragePolicyRequestAddressingStyle,
)

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ExternalStoragePoliciesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawExternalStoragePoliciesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawExternalStoragePoliciesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawExternalStoragePoliciesClient
        """
        return self._raw_client

    def list(
        self, *, project: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ExternalStoragePoliciesListResponse:
        """
        Returns all external storage policies in a project.

        Parameters
        ----------
        project : typing.Optional[str]
            The name of the project to list external storage policies for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalStoragePoliciesListResponse
            Success response

        Examples
        --------
        from phonic import Phonic

        client = Phonic(
            api_key="YOUR_API_KEY",
        )
        client.external_storage_policies.list(
            project="main",
        )
        """
        _response = self._raw_client.list(project=project, request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        name: str,
        endpoint_url: str,
        bucket: str,
        access_key_id: str,
        secret_access_key: str,
        project: typing.Optional[str] = None,
        region: typing.Optional[str] = OMIT,
        key_prefix: typing.Optional[str] = OMIT,
        addressing_style: typing.Optional[CreateExternalStoragePolicyRequestAddressingStyle] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExternalStoragePoliciesCreateResponse:
        """
        Creates a new external storage policy in a project. Agents referencing the policy deliver their conversation artifacts to the configured S3-compatible bucket.

        Parameters
        ----------
        name : str
            The name of the external storage policy. Must be snake_case, start with a lowercase letter and be unique within the project.

        endpoint_url : str
            The S3-compatible endpoint URL that artifacts are uploaded to. Must be a publicly routable HTTPS URL without embedded credentials.

        bucket : str
            The bucket that artifacts are uploaded to.

        access_key_id : str
            Access key ID used to authenticate with the endpoint. Stored encrypted and never returned.

        secret_access_key : str
            Secret access key used to authenticate with the endpoint. Stored encrypted and never returned.

        project : typing.Optional[str]
            The name of the project to create the external storage policy in.

        region : typing.Optional[str]
            The region of the bucket. Set to `null` when the endpoint doesn't require a region.

        key_prefix : typing.Optional[str]
            Prefix prepended to every object key.

        addressing_style : typing.Optional[CreateExternalStoragePolicyRequestAddressingStyle]
            How bucket names are addressed in requests to the endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalStoragePoliciesCreateResponse
            Success response

        Examples
        --------
        from phonic import Phonic

        client = Phonic(
            api_key="YOUR_API_KEY",
        )
        client.external_storage_policies.create(
            project="main",
            name="conversation_archive",
            endpoint_url="https://storage.example.com",
            bucket="conversation-audio",
            region="us-east-1",
            key_prefix="phonic/conversations",
            addressing_style="auto",
            access_key_id="AKIAIOSFODNN7EXAMPLE",
            secret_access_key="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
        )
        """
        _response = self._raw_client.create(
            name=name,
            endpoint_url=endpoint_url,
            bucket=bucket,
            access_key_id=access_key_id,
            secret_access_key=secret_access_key,
            project=project,
            region=region,
            key_prefix=key_prefix,
            addressing_style=addressing_style,
            request_options=request_options,
        )
        return _response.data

    def get(
        self,
        name_or_id: str,
        *,
        project: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExternalStoragePoliciesGetResponse:
        """
        Returns an external storage policy by name or ID.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the external storage policy to get.

        project : typing.Optional[str]
            The name of the project containing the external storage policy. Only used when `nameOrId` is a name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalStoragePoliciesGetResponse
            Success response

        Examples
        --------
        from phonic import Phonic

        client = Phonic(
            api_key="YOUR_API_KEY",
        )
        client.external_storage_policies.get(
            name_or_id="nameOrId",
            project="main",
        )
        """
        _response = self._raw_client.get(name_or_id, project=project, request_options=request_options)
        return _response.data

    def delete(
        self,
        name_or_id: str,
        *,
        project: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExternalStoragePoliciesDeleteResponse:
        """
        Deletes an external storage policy by name or ID. The policy must not be referenced by any agent.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the external storage policy to delete.

        project : typing.Optional[str]
            The name of the project containing the external storage policy. Only used when `nameOrId` is a name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalStoragePoliciesDeleteResponse
            Success response

        Examples
        --------
        from phonic import Phonic

        client = Phonic(
            api_key="YOUR_API_KEY",
        )
        client.external_storage_policies.delete(
            name_or_id="nameOrId",
            project="main",
        )
        """
        _response = self._raw_client.delete(name_or_id, project=project, request_options=request_options)
        return _response.data

    def update(
        self,
        name_or_id: str,
        *,
        project: typing.Optional[str] = None,
        name: typing.Optional[str] = OMIT,
        endpoint_url: typing.Optional[str] = OMIT,
        bucket: typing.Optional[str] = OMIT,
        region: typing.Optional[str] = OMIT,
        key_prefix: typing.Optional[str] = OMIT,
        addressing_style: typing.Optional[UpdateExternalStoragePolicyRequestAddressingStyle] = OMIT,
        access_key_id: typing.Optional[str] = OMIT,
        secret_access_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExternalStoragePoliciesUpdateResponse:
        """
        Updates an external storage policy by name or ID. Credentials can only be rotated by providing both `access_key_id` and `secret_access_key`.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the external storage policy to update.

        project : typing.Optional[str]
            The name of the project containing the external storage policy. Only used when `nameOrId` is a name.

        name : typing.Optional[str]
            The name of the external storage policy. Must be snake_case, start with a lowercase letter and be unique within the project.

        endpoint_url : typing.Optional[str]
            The S3-compatible endpoint URL that artifacts are uploaded to. Must be a publicly routable HTTPS URL without embedded credentials.

        bucket : typing.Optional[str]
            The bucket that artifacts are uploaded to.

        region : typing.Optional[str]
            The region of the bucket. Set to `null` when the endpoint doesn't require a region.

        key_prefix : typing.Optional[str]
            Prefix prepended to every object key.

        addressing_style : typing.Optional[UpdateExternalStoragePolicyRequestAddressingStyle]
            How bucket names are addressed in requests to the endpoint.

        access_key_id : typing.Optional[str]
            Access key ID used to authenticate with the endpoint. Must be provided together with `secret_access_key`.

        secret_access_key : typing.Optional[str]
            Secret access key used to authenticate with the endpoint. Must be provided together with `access_key_id`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalStoragePoliciesUpdateResponse
            Success response

        Examples
        --------
        from phonic import Phonic

        client = Phonic(
            api_key="YOUR_API_KEY",
        )
        client.external_storage_policies.update(
            name_or_id="nameOrId",
            project="main",
            bucket="conversation-audio-archive",
            key_prefix="phonic/archive",
        )
        """
        _response = self._raw_client.update(
            name_or_id,
            project=project,
            name=name,
            endpoint_url=endpoint_url,
            bucket=bucket,
            region=region,
            key_prefix=key_prefix,
            addressing_style=addressing_style,
            access_key_id=access_key_id,
            secret_access_key=secret_access_key,
            request_options=request_options,
        )
        return _response.data


class AsyncExternalStoragePoliciesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawExternalStoragePoliciesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawExternalStoragePoliciesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawExternalStoragePoliciesClient
        """
        return self._raw_client

    async def list(
        self, *, project: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ExternalStoragePoliciesListResponse:
        """
        Returns all external storage policies in a project.

        Parameters
        ----------
        project : typing.Optional[str]
            The name of the project to list external storage policies for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalStoragePoliciesListResponse
            Success response

        Examples
        --------
        import asyncio

        from phonic import AsyncPhonic

        client = AsyncPhonic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.external_storage_policies.list(
                project="main",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(project=project, request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        name: str,
        endpoint_url: str,
        bucket: str,
        access_key_id: str,
        secret_access_key: str,
        project: typing.Optional[str] = None,
        region: typing.Optional[str] = OMIT,
        key_prefix: typing.Optional[str] = OMIT,
        addressing_style: typing.Optional[CreateExternalStoragePolicyRequestAddressingStyle] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExternalStoragePoliciesCreateResponse:
        """
        Creates a new external storage policy in a project. Agents referencing the policy deliver their conversation artifacts to the configured S3-compatible bucket.

        Parameters
        ----------
        name : str
            The name of the external storage policy. Must be snake_case, start with a lowercase letter and be unique within the project.

        endpoint_url : str
            The S3-compatible endpoint URL that artifacts are uploaded to. Must be a publicly routable HTTPS URL without embedded credentials.

        bucket : str
            The bucket that artifacts are uploaded to.

        access_key_id : str
            Access key ID used to authenticate with the endpoint. Stored encrypted and never returned.

        secret_access_key : str
            Secret access key used to authenticate with the endpoint. Stored encrypted and never returned.

        project : typing.Optional[str]
            The name of the project to create the external storage policy in.

        region : typing.Optional[str]
            The region of the bucket. Set to `null` when the endpoint doesn't require a region.

        key_prefix : typing.Optional[str]
            Prefix prepended to every object key.

        addressing_style : typing.Optional[CreateExternalStoragePolicyRequestAddressingStyle]
            How bucket names are addressed in requests to the endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalStoragePoliciesCreateResponse
            Success response

        Examples
        --------
        import asyncio

        from phonic import AsyncPhonic

        client = AsyncPhonic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.external_storage_policies.create(
                project="main",
                name="conversation_archive",
                endpoint_url="https://storage.example.com",
                bucket="conversation-audio",
                region="us-east-1",
                key_prefix="phonic/conversations",
                addressing_style="auto",
                access_key_id="AKIAIOSFODNN7EXAMPLE",
                secret_access_key="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name,
            endpoint_url=endpoint_url,
            bucket=bucket,
            access_key_id=access_key_id,
            secret_access_key=secret_access_key,
            project=project,
            region=region,
            key_prefix=key_prefix,
            addressing_style=addressing_style,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self,
        name_or_id: str,
        *,
        project: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExternalStoragePoliciesGetResponse:
        """
        Returns an external storage policy by name or ID.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the external storage policy to get.

        project : typing.Optional[str]
            The name of the project containing the external storage policy. Only used when `nameOrId` is a name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalStoragePoliciesGetResponse
            Success response

        Examples
        --------
        import asyncio

        from phonic import AsyncPhonic

        client = AsyncPhonic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.external_storage_policies.get(
                name_or_id="nameOrId",
                project="main",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(name_or_id, project=project, request_options=request_options)
        return _response.data

    async def delete(
        self,
        name_or_id: str,
        *,
        project: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExternalStoragePoliciesDeleteResponse:
        """
        Deletes an external storage policy by name or ID. The policy must not be referenced by any agent.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the external storage policy to delete.

        project : typing.Optional[str]
            The name of the project containing the external storage policy. Only used when `nameOrId` is a name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalStoragePoliciesDeleteResponse
            Success response

        Examples
        --------
        import asyncio

        from phonic import AsyncPhonic

        client = AsyncPhonic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.external_storage_policies.delete(
                name_or_id="nameOrId",
                project="main",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(name_or_id, project=project, request_options=request_options)
        return _response.data

    async def update(
        self,
        name_or_id: str,
        *,
        project: typing.Optional[str] = None,
        name: typing.Optional[str] = OMIT,
        endpoint_url: typing.Optional[str] = OMIT,
        bucket: typing.Optional[str] = OMIT,
        region: typing.Optional[str] = OMIT,
        key_prefix: typing.Optional[str] = OMIT,
        addressing_style: typing.Optional[UpdateExternalStoragePolicyRequestAddressingStyle] = OMIT,
        access_key_id: typing.Optional[str] = OMIT,
        secret_access_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExternalStoragePoliciesUpdateResponse:
        """
        Updates an external storage policy by name or ID. Credentials can only be rotated by providing both `access_key_id` and `secret_access_key`.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the external storage policy to update.

        project : typing.Optional[str]
            The name of the project containing the external storage policy. Only used when `nameOrId` is a name.

        name : typing.Optional[str]
            The name of the external storage policy. Must be snake_case, start with a lowercase letter and be unique within the project.

        endpoint_url : typing.Optional[str]
            The S3-compatible endpoint URL that artifacts are uploaded to. Must be a publicly routable HTTPS URL without embedded credentials.

        bucket : typing.Optional[str]
            The bucket that artifacts are uploaded to.

        region : typing.Optional[str]
            The region of the bucket. Set to `null` when the endpoint doesn't require a region.

        key_prefix : typing.Optional[str]
            Prefix prepended to every object key.

        addressing_style : typing.Optional[UpdateExternalStoragePolicyRequestAddressingStyle]
            How bucket names are addressed in requests to the endpoint.

        access_key_id : typing.Optional[str]
            Access key ID used to authenticate with the endpoint. Must be provided together with `secret_access_key`.

        secret_access_key : typing.Optional[str]
            Secret access key used to authenticate with the endpoint. Must be provided together with `access_key_id`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExternalStoragePoliciesUpdateResponse
            Success response

        Examples
        --------
        import asyncio

        from phonic import AsyncPhonic

        client = AsyncPhonic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.external_storage_policies.update(
                name_or_id="nameOrId",
                project="main",
                bucket="conversation-audio-archive",
                key_prefix="phonic/archive",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            name_or_id,
            project=project,
            name=name,
            endpoint_url=endpoint_url,
            bucket=bucket,
            region=region,
            key_prefix=key_prefix,
            addressing_style=addressing_style,
            access_key_id=access_key_id,
            secret_access_key=secret_access_key,
            request_options=request_options,
        )
        return _response.data
