# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.parse_error import ParsingError
from ..core.request_options import RequestOptions
from ..core.unchecked_base_model import construct_type
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.basic_error import BasicError
from .types.create_external_storage_policy_request_addressing_style import (
    CreateExternalStoragePolicyRequestAddressingStyle,
)
from .types.external_storage_policies_create_response import ExternalStoragePoliciesCreateResponse
from .types.external_storage_policies_delete_response import ExternalStoragePoliciesDeleteResponse
from .types.external_storage_policies_get_response import ExternalStoragePoliciesGetResponse
from .types.external_storage_policies_list_response import ExternalStoragePoliciesListResponse
from .types.external_storage_policies_update_response import ExternalStoragePoliciesUpdateResponse
from .types.update_external_storage_policy_request_addressing_style import (
    UpdateExternalStoragePolicyRequestAddressingStyle,
)
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawExternalStoragePoliciesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self, *, project: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ExternalStoragePoliciesListResponse]:
        """
        Returns all external storage policies in a project.

        Parameters
        ----------
        project : typing.Optional[str]
            The name of the project to list external storage policies for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ExternalStoragePoliciesListResponse]
            Success response
        """
        _response = self._client_wrapper.httpx_client.request(
            "external_storage_policies",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "project": project,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExternalStoragePoliciesListResponse,
                    construct_type(
                        type_=ExternalStoragePoliciesListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        name: str,
        endpoint_url: str,
        bucket: str,
        access_key_id: str,
        secret_access_key: str,
        project: typing.Optional[str] = None,
        region: typing.Optional[str] = OMIT,
        key_prefix: typing.Optional[str] = OMIT,
        addressing_style: typing.Optional[CreateExternalStoragePolicyRequestAddressingStyle] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ExternalStoragePoliciesCreateResponse]:
        """
        Creates a new external storage policy in a project. Agents referencing the policy deliver their conversation artifacts to the configured S3-compatible bucket.

        Parameters
        ----------
        name : str
            The name of the external storage policy. Must be snake_case, start with a lowercase letter and be unique within the project.

        endpoint_url : str
            The S3-compatible endpoint URL that artifacts are uploaded to. Must be a publicly routable HTTPS URL without embedded credentials.

        bucket : str
            The bucket that artifacts are uploaded to.

        access_key_id : str
            Access key ID used to authenticate with the endpoint. Stored encrypted and never returned.

        secret_access_key : str
            Secret access key used to authenticate with the endpoint. Stored encrypted and never returned.

        project : typing.Optional[str]
            The name of the project to create the external storage policy in.

        region : typing.Optional[str]
            The region of the bucket. Set to `null` when the endpoint doesn't require a region.

        key_prefix : typing.Optional[str]
            Prefix prepended to every object key.

        addressing_style : typing.Optional[CreateExternalStoragePolicyRequestAddressingStyle]
            How bucket names are addressed in requests to the endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ExternalStoragePoliciesCreateResponse]
            Success response
        """
        _response = self._client_wrapper.httpx_client.request(
            "external_storage_policies",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            params={
                "project": project,
            },
            json={
                "name": name,
                "endpoint_url": endpoint_url,
                "bucket": bucket,
                "region": region,
                "key_prefix": key_prefix,
                "addressing_style": addressing_style,
                "access_key_id": access_key_id,
                "secret_access_key": secret_access_key,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExternalStoragePoliciesCreateResponse,
                    construct_type(
                        type_=ExternalStoragePoliciesCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self,
        name_or_id: str,
        *,
        project: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ExternalStoragePoliciesGetResponse]:
        """
        Returns an external storage policy by name or ID.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the external storage policy to get.

        project : typing.Optional[str]
            The name of the project containing the external storage policy. Only used when `nameOrId` is a name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ExternalStoragePoliciesGetResponse]
            Success response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"external_storage_policies/{jsonable_encoder(name_or_id)}",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "project": project,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExternalStoragePoliciesGetResponse,
                    construct_type(
                        type_=ExternalStoragePoliciesGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self,
        name_or_id: str,
        *,
        project: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ExternalStoragePoliciesDeleteResponse]:
        """
        Deletes an external storage policy by name or ID. The policy must not be referenced by any agent.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the external storage policy to delete.

        project : typing.Optional[str]
            The name of the project containing the external storage policy. Only used when `nameOrId` is a name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ExternalStoragePoliciesDeleteResponse]
            Success response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"external_storage_policies/{jsonable_encoder(name_or_id)}",
            base_url=self._client_wrapper.get_environment().base,
            method="DELETE",
            params={
                "project": project,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExternalStoragePoliciesDeleteResponse,
                    construct_type(
                        type_=ExternalStoragePoliciesDeleteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        name_or_id: str,
        *,
        project: typing.Optional[str] = None,
        name: typing.Optional[str] = OMIT,
        endpoint_url: typing.Optional[str] = OMIT,
        bucket: typing.Optional[str] = OMIT,
        region: typing.Optional[str] = OMIT,
        key_prefix: typing.Optional[str] = OMIT,
        addressing_style: typing.Optional[UpdateExternalStoragePolicyRequestAddressingStyle] = OMIT,
        access_key_id: typing.Optional[str] = OMIT,
        secret_access_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ExternalStoragePoliciesUpdateResponse]:
        """
        Updates an external storage policy by name or ID. Credentials can only be rotated by providing both `access_key_id` and `secret_access_key`.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the external storage policy to update.

        project : typing.Optional[str]
            The name of the project containing the external storage policy. Only used when `nameOrId` is a name.

        name : typing.Optional[str]
            The name of the external storage policy. Must be snake_case, start with a lowercase letter and be unique within the project.

        endpoint_url : typing.Optional[str]
            The S3-compatible endpoint URL that artifacts are uploaded to. Must be a publicly routable HTTPS URL without embedded credentials.

        bucket : typing.Optional[str]
            The bucket that artifacts are uploaded to.

        region : typing.Optional[str]
            The region of the bucket. Set to `null` when the endpoint doesn't require a region.

        key_prefix : typing.Optional[str]
            Prefix prepended to every object key.

        addressing_style : typing.Optional[UpdateExternalStoragePolicyRequestAddressingStyle]
            How bucket names are addressed in requests to the endpoint.

        access_key_id : typing.Optional[str]
            Access key ID used to authenticate with the endpoint. Must be provided together with `secret_access_key`.

        secret_access_key : typing.Optional[str]
            Secret access key used to authenticate with the endpoint. Must be provided together with `access_key_id`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ExternalStoragePoliciesUpdateResponse]
            Success response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"external_storage_policies/{jsonable_encoder(name_or_id)}",
            base_url=self._client_wrapper.get_environment().base,
            method="PATCH",
            params={
                "project": project,
            },
            json={
                "name": name,
                "endpoint_url": endpoint_url,
                "bucket": bucket,
                "region": region,
                "key_prefix": key_prefix,
                "addressing_style": addressing_style,
                "access_key_id": access_key_id,
                "secret_access_key": secret_access_key,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExternalStoragePoliciesUpdateResponse,
                    construct_type(
                        type_=ExternalStoragePoliciesUpdateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawExternalStoragePoliciesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self, *, project: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ExternalStoragePoliciesListResponse]:
        """
        Returns all external storage policies in a project.

        Parameters
        ----------
        project : typing.Optional[str]
            The name of the project to list external storage policies for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ExternalStoragePoliciesListResponse]
            Success response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "external_storage_policies",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "project": project,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExternalStoragePoliciesListResponse,
                    construct_type(
                        type_=ExternalStoragePoliciesListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        name: str,
        endpoint_url: str,
        bucket: str,
        access_key_id: str,
        secret_access_key: str,
        project: typing.Optional[str] = None,
        region: typing.Optional[str] = OMIT,
        key_prefix: typing.Optional[str] = OMIT,
        addressing_style: typing.Optional[CreateExternalStoragePolicyRequestAddressingStyle] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ExternalStoragePoliciesCreateResponse]:
        """
        Creates a new external storage policy in a project. Agents referencing the policy deliver their conversation artifacts to the configured S3-compatible bucket.

        Parameters
        ----------
        name : str
            The name of the external storage policy. Must be snake_case, start with a lowercase letter and be unique within the project.

        endpoint_url : str
            The S3-compatible endpoint URL that artifacts are uploaded to. Must be a publicly routable HTTPS URL without embedded credentials.

        bucket : str
            The bucket that artifacts are uploaded to.

        access_key_id : str
            Access key ID used to authenticate with the endpoint. Stored encrypted and never returned.

        secret_access_key : str
            Secret access key used to authenticate with the endpoint. Stored encrypted and never returned.

        project : typing.Optional[str]
            The name of the project to create the external storage policy in.

        region : typing.Optional[str]
            The region of the bucket. Set to `null` when the endpoint doesn't require a region.

        key_prefix : typing.Optional[str]
            Prefix prepended to every object key.

        addressing_style : typing.Optional[CreateExternalStoragePolicyRequestAddressingStyle]
            How bucket names are addressed in requests to the endpoint.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ExternalStoragePoliciesCreateResponse]
            Success response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "external_storage_policies",
            base_url=self._client_wrapper.get_environment().base,
            method="POST",
            params={
                "project": project,
            },
            json={
                "name": name,
                "endpoint_url": endpoint_url,
                "bucket": bucket,
                "region": region,
                "key_prefix": key_prefix,
                "addressing_style": addressing_style,
                "access_key_id": access_key_id,
                "secret_access_key": secret_access_key,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExternalStoragePoliciesCreateResponse,
                    construct_type(
                        type_=ExternalStoragePoliciesCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self,
        name_or_id: str,
        *,
        project: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ExternalStoragePoliciesGetResponse]:
        """
        Returns an external storage policy by name or ID.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the external storage policy to get.

        project : typing.Optional[str]
            The name of the project containing the external storage policy. Only used when `nameOrId` is a name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ExternalStoragePoliciesGetResponse]
            Success response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"external_storage_policies/{jsonable_encoder(name_or_id)}",
            base_url=self._client_wrapper.get_environment().base,
            method="GET",
            params={
                "project": project,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExternalStoragePoliciesGetResponse,
                    construct_type(
                        type_=ExternalStoragePoliciesGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self,
        name_or_id: str,
        *,
        project: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ExternalStoragePoliciesDeleteResponse]:
        """
        Deletes an external storage policy by name or ID. The policy must not be referenced by any agent.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the external storage policy to delete.

        project : typing.Optional[str]
            The name of the project containing the external storage policy. Only used when `nameOrId` is a name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ExternalStoragePoliciesDeleteResponse]
            Success response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"external_storage_policies/{jsonable_encoder(name_or_id)}",
            base_url=self._client_wrapper.get_environment().base,
            method="DELETE",
            params={
                "project": project,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExternalStoragePoliciesDeleteResponse,
                    construct_type(
                        type_=ExternalStoragePoliciesDeleteResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        name_or_id: str,
        *,
        project: typing.Optional[str] = None,
        name: typing.Optional[str] = OMIT,
        endpoint_url: typing.Optional[str] = OMIT,
        bucket: typing.Optional[str] = OMIT,
        region: typing.Optional[str] = OMIT,
        key_prefix: typing.Optional[str] = OMIT,
        addressing_style: typing.Optional[UpdateExternalStoragePolicyRequestAddressingStyle] = OMIT,
        access_key_id: typing.Optional[str] = OMIT,
        secret_access_key: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ExternalStoragePoliciesUpdateResponse]:
        """
        Updates an external storage policy by name or ID. Credentials can only be rotated by providing both `access_key_id` and `secret_access_key`.

        Parameters
        ----------
        name_or_id : str
            The name or the ID of the external storage policy to update.

        project : typing.Optional[str]
            The name of the project containing the external storage policy. Only used when `nameOrId` is a name.

        name : typing.Optional[str]
            The name of the external storage policy. Must be snake_case, start with a lowercase letter and be unique within the project.

        endpoint_url : typing.Optional[str]
            The S3-compatible endpoint URL that artifacts are uploaded to. Must be a publicly routable HTTPS URL without embedded credentials.

        bucket : typing.Optional[str]
            The bucket that artifacts are uploaded to.

        region : typing.Optional[str]
            The region of the bucket. Set to `null` when the endpoint doesn't require a region.

        key_prefix : typing.Optional[str]
            Prefix prepended to every object key.

        addressing_style : typing.Optional[UpdateExternalStoragePolicyRequestAddressingStyle]
            How bucket names are addressed in requests to the endpoint.

        access_key_id : typing.Optional[str]
            Access key ID used to authenticate with the endpoint. Must be provided together with `secret_access_key`.

        secret_access_key : typing.Optional[str]
            Secret access key used to authenticate with the endpoint. Must be provided together with `access_key_id`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ExternalStoragePoliciesUpdateResponse]
            Success response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"external_storage_policies/{jsonable_encoder(name_or_id)}",
            base_url=self._client_wrapper.get_environment().base,
            method="PATCH",
            params={
                "project": project,
            },
            json={
                "name": name,
                "endpoint_url": endpoint_url,
                "bucket": bucket,
                "region": region,
                "key_prefix": key_prefix,
                "addressing_style": addressing_style,
                "access_key_id": access_key_id,
                "secret_access_key": secret_access_key,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExternalStoragePoliciesUpdateResponse,
                    construct_type(
                        type_=ExternalStoragePoliciesUpdateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        construct_type(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        BasicError,
                        construct_type(
                            type_=BasicError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
