# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ExternalStoragePoliciesUpdateResponseParams(typing_extensions.TypedDict):
    success: bool
    """
    Whether the external storage policy was updated successfully.
    """
