# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...requests.external_storage_policy import ExternalStoragePolicyParams


class ExternalStoragePoliciesGetResponseParams(typing_extensions.TypedDict):
    external_storage_policy: ExternalStoragePolicyParams
