# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ExternalStoragePoliciesCreateResponseParams(typing_extensions.TypedDict):
    id: str
    """
    The ID of the created external storage policy.
    """

    name: str
    """
    The name of the created external storage policy.
    """
