# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class WorkspaceGetResponseParams(typing_extensions.TypedDict):
    active_conversations: int
    """
    Number of conversations currently in progress for this workspace.
    """

    max_active_conversations: int
    """
    Maximum number of concurrent conversations allowed for this workspace.
    """

    logo_url: typing.Optional[str]
    """
    URL of the workspace logo (PNG or SVG), or null if not set.
    """

    invite_link_allowed_domains: typing.Sequence[str]
    """
    Email domains allowed to join the workspace via invite link.
    """

    ip_allowlist: typing.Sequence[str]
    """
    IP addresses or CIDR ranges allowed to access the workspace.
    """
