# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class WorkspaceGetResponseParams(typing_extensions.TypedDict):
    active_conversations: int
    """
    Number of conversations currently in progress for this workspace.
    """

    max_active_conversations: int
    """
    Maximum number of concurrent conversations allowed for this workspace.
    """
