# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.tool_parameter import ToolParameter
from ...types.tool_parameters_json_schema import ToolParametersJsonSchema

UpdateToolRequestParameters = typing.Union[typing.List[ToolParameter], ToolParametersJsonSchema]
